plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
}

dependencies {
    implementation project(":core:common")
    implementation libs.kotlinx.coroutines.test
    implementation libs.hamcrest
    implementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
}
