apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation project(":core:common")
    implementation project(":core:domain")
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6'
    // for test matching
    testImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'
    // for unit tests
    testImplementation 'junit:junit:4.13'
    // coroutine support for tests
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.6'
    // mock libraries
    testImplementation 'org.mockito:mockito-core:3.9.0'
    testImplementation "org.mockito.kotlin:mockito-kotlin:4.0.0"
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
sourceCompatibility = "8"
targetCompatibility = "8"
