plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.kotlin.stdlib
    implementation project(":core:common")
    implementation project(":core:domain")
    implementation libs.kotlinx.coroutines.core
    testImplementation libs.hamcrest
    testImplementation libs.junit4
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
}
