plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.ksp)
}

android {
    compileSdkVersion 31

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    flavorDimensions "version"
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
    }
    productFlavors {
        mock
        full
    }

    android {
        // this is needed because including
        // androidTestImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.6'
        // leaves duplicate files in same path as other libraries, it was not a problem at 1.3.5
        packagingOptions {
            exclude 'META-INF/AL2.0'
            exclude 'META-INF/LGPL2.1'
            exclude "META-INF/licenses/**"
            exclude "**/attach_hotspot_windows.dll"
        }
        sourceSets {
            // Adds exported schema location as test app assets.
            androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    namespace 'eu.kalnarapps.kalnardict.localdata'

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:data")
    implementation project(":core:common")
    implementation project(":platform:android:common")
    androidTestImplementation project(":platform:androidtest")
    androidTestImplementation project(":core:test")

    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    androidTestImplementation libs.hamcrest
    testImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation(libs.androidx.test.ext.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation(libs.androidx.espresso.core) {
        exclude group: 'org.hamcrest'
    }

    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler
    kspAndroidTest libs.androidx.room.compiler

    androidTestImplementation(libs.androidx.room.testing) {
        exclude group: 'org.hamcrest'
    }

    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.guava
    testImplementation libs.androidx.room.testing

    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    androidTestImplementation libs.kotlinx.coroutines.test
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.junit.jupiter.api

    androidTestImplementation(libs.support.test.rules) {
        exclude group: 'org.hamcrest'
    }

    implementation libs.koin.core

    implementation libs.mockito.core

    implementation libs.androidx.preference.ktx
    implementation libs.flow.preferences
}
