plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.ksp)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:domain")
    implementation project(":core:common")

    implementation libs.kotlin.stdlib

    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler

    testImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation(libs.androidx.test.ext.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation(libs.androidx.espresso.core) {
        exclude group: 'org.hamcrest'
    }
    testImplementation libs.kotlinx.coroutines.test

    implementation libs.koin.core
    implementation libs.koin.core.ext

    testImplementation libs.mockito.core
    testImplementation libs.mockito.inline
    testImplementation libs.mockito.kotlin
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
}
