create TABLE meta_info(
   id INTEGER PRIMARY KEY NOT NULL,
   dictionary_name TEXT NOT NULL,
   language_from TEXT NOT NULL,
   language_to TEXT NOT NULL,
   version TEXT NOT NULL
);

create TABLE test_fr_dictionary(
   id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   base_form TEXT NOT NULL,
   base_form_alt TEXT NOT NULL,
   translation TEXT NOT NULL
);

insert into
    test_fr_dictionary (base_form,base_form_alt,translation)
values
    ("le", "le", "(det.) the; (pron.) him, her, it, them"),
    ("de", "de", "(det.) some, any; (prep.) of, from"),
    ("un", "un", "(det.) a, an; (adj., pron.) one"),
    ("à ", "à", "(prep.) to, at, in"),
    ("être", "être", "(verb) to be; (noun [m.]) being"),
    ("et", "et", "(conj.) and"),
    ("en", "en", "(prep.) in, by; (adv., pron.)"),
    ("avoir", "avoir", "(verb) to have; (noun [m.]) assets"),
    ("que", "que", "(adv., pron., conj.) that, which, who, whom"),
    ("pour", "pour", "(prep.) for, in order to"),
    ("dans", "dans", "(prep.) in, into, from"),
    ("ce", "ce", "(det., pron.) this, that"),
    ("il", "il", "(pron.) he, it"),
    ("qui", "qui", "(pron.) who, whom"),
    ("ne", "ne", "(adv.) not"),
    ("sur", "sur", "(prep.) on, upon; (adj.) sour"),
    ("se", "se", "(pron.) oneself, himself, herself, itself, themselves"),
    ("pas", "pas", "(adv.) not; (noun [m.]) footstep"),
    ("plus", "plus", "(adv.) more, no more"),
    ("pouvoir", "pouvoir", "(verb) to be able to, can; (noun [m.]) power"),
    ("par", "par", "(prep.) by"),
    ("je", "je", "(pron.) I"),
    ("avec", "avec", "(prep.) with"),
    ("tout", "tout", "(adj., adv., pron., det.) all, very"),
    ("faire", "faire", "(verb) to do, make"),
    ("son", "son", "(det.) his, her its; (noun [m.]) sound; bran"),
    ("mettre", "mettre", "(verb) to put, place"),
    ("autre", "autre", "(det., pron.) other"),
    ("on", "on", "(pron.) one, we"),
    ("mais", "mais", "(conj., adv.) but"),
    ("nous", "nous", "(pron.) we, us"),
    ("comme", "comme", "(conj., adv.) like, as"),
    ("ou", "ou", "(conj.) or"),
    ("si", "si", "(conj.) if, whether; (adv.) so"),
    ("leur", "leur", "(det., pron.) their, theirs, them"),
    ("y", "y", "(adv.) there; (pron.) it"),
    ("dire", "dire", "(verb) to say; (noun [m.]) saying"),
    ("elle", "elle", "(pron.) she, her"),
    ("devoir", "devoir", "(verb) to have to, owe; (noun [m.]) duty"),
    ("avant", "avant", "(prep., adv.) before; (noun [m.]) front"),
    ("deux", "deux", "(det., noun [m.]) two"),
    ("même", "même", "(adj., pron.) same; (adv.) even"),
    ("prendre", "prendre", "(verb) to take"),
    ("aussi", "aussi", "(adv.) to, also; (conj.) as"),
    ("celui", "celui", "(pron.) that, the one, he, him"),
    ("donner", "donner", "(verb) to give"),
    ("bien", "bien", "(adv.) well; (noun [m.]) good"),
    ("où", "où", "(adv., pron.) where"),
    ("fois", "fois", "(noun [f.]) time(s)"),
    ("vous", "vous", "(pron.) you"),
    ("encore", "encore", "(adv.) again, yet"),
    ("nouveau", "nouveau", "(adj.) new; (noun [m.]) new (thing)"),
    ("aller", "aller", "(verb) to go"),
    ("cela", "cela", "(pron.) that, it"),
    ("entre", "entre", "(prep.) between"),
    ("premier", "premier", "(det., adj.) first"),
    ("vouloir", "vouloir", "(verb) to want; (noun [m.]) will, desire"),
    ("déjà", "déjà", "(adv.) already"),
    ("grand", "grand", "(adj., adv.) great, big, tall"),
    ("mon", "mon", "(det.) my"),
    ("me", "me", "(pron.) me, to me, myself"),
    ("moins", "moins", "(adv.) less; (prep., noun [m.]) minus"),
    ("aucun", "aucun", "(det., adj., pron.) none, either, neither, not any"),
    ("lui", "lui", "(pron.) him, her"),
    ("temps", "temps", "(noun [m.]) time"),
    ("très", "très", "(adv.) very"),
    ("savoir", "savoir", "(verb) to know; (noun [m.]) learning, knowledge"),
    ("falloir", "falloir", "(verb) to take, require, need"),
    ("voir", "voir", "(verb) to see"),
    ("quelque", "quelque", "(det., adj., adv.) some"),
    ("sans", "sans", "(prep.) without"),
    ("raison", "raison", "(noun [f.]) reason"),
    ("notre", "notre", "(det.) our"),
    ("dont", "dont", "(pron.) whose, of which"),
    ("non", "non", "(adv.) no, not"),
    ("an", "an", "(noun [m.]) year"),
    ("monde", "monde", "(noun [m.]) world, people"),
    ("jour", "jour", "(noun [m.]) day"),
    ("monsieur", "monsieur", "(noun [m.]) mister, sir, gentleman"),
    ("demander", "demander", "(verb) to ask for"),
    ("alors", "alors", "(adv.) then, so"),
    ("après", "après", "(adv., prep.) after"),
    ("trouver", "trouver", "(verb) to find"),
    ("personne", "personne", "(noun [f.]) person; (pron.) anyone, nobody"),
    ("rendre", "rendre", "(verb) to render, return, yield, give up"),
    ("part", "part", "(noun [f.]) share"),
    ("dernier", "dernier", "(adj). last"),
    ("venir", "venir", "(verb) to come"),
    ("pendant", "pendant", "(adj.) during; (prep.) for; (noun [m.]) pendant"),
    ("passer", "passer", "(verb) to pass"),
    ("peu", "peu", "(adv.) little"),
    ("lequel", "lequel", "(pron.) who, whom, which"),
    ("suite", "suite", "(noun [f.]) result, follow-up, rest"),
    ("bon", "bon", "(adj., adv.) good; (noun [m.]) coupon, voucher"),
    ("comprendre", "comprendre", "(verb) to understand"),
    ("depuis", "depuis", "(prep., adv.) since"),
    ("point", "point", "(adv.) at all; (noun [m.]) point"),
    ("ainsi", "ainsi", "(adv.) thus"),
    ("heure", "heure", "(noun [f.]) hour"),
    ("rester", "rester", "(verb) to stay");

insert into
    meta_info (id,dictionary_name,language_from,language_to,version)
values
    (1,"test_fr_dictionary","French","English","0.01");
