create TABLE meta_info(
   id INTEGER PRIMARY KEY NOT NULL,
   dictionary_name TEXT NOT NULL,
   language_from TEXT NOT NULL,
   language_to TEXT NOT NULL,
   version TEXT NOT NULL
);

create TABLE test_fr_dictionary(
   id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   base_form TEXT NOT NULL,
   base_form_alt TEXT NOT NULL,
   translation TEXT NOT NULL,
   dictionary_id INTEGER NOT NULL,
   FOREIGN KEY(dictionary_id) REFERENCES meta_info(id)
);

insert into
    meta_info (id,dictionary_name,language_from,language_to,version)
values
    (1,"test_fr_dictionary","French","English","0.01");

insert into
    test_fr_dictionary (base_form,base_form_alt,translation,dictionary_id)
values
    ("le", "le", "(det.) the; (pron.) him, her, it, them", 1),
    ("de", "de", "(det.) some, any; (prep.) of, from", 1),
    ("un", "un", "(det.) a, an; (adj., pron.) one", 1),
    ("à ", "à", "(prep.) to, at, in", 1),
    ("être", "être", "(verb) to be; (noun [m.]) being", 1),
    ("et", "et", "(conj.) and", 1),
    ("en", "en", "(prep.) in, by; (adv., pron.)", 1),
    ("avoir", "avoir", "(verb) to have; (noun [m.]) assets", 1),
    ("que", "que", "(adv., pron., conj.) that, which, who, whom", 1),
    ("pour", "pour", "(prep.) for, in order to", 1),
    ("dans", "dans", "(prep.) in, into, from", 1),
    ("ce", "ce", "(det., pron.) this, that", 1),
    ("il", "il", "(pron.) he, it", 1),
    ("qui", "qui", "(pron.) who, whom", 1),
    ("ne", "ne", "(adv.) not", 1),
    ("sur", "sur", "(prep.) on, upon; (adj.) sour", 1),
    ("se", "se", "(pron.) oneself, himself, herself, itself, themselves", 1),
    ("pas", "pas", "(adv.) not; (noun [m.]) footstep", 1),
    ("plus", "plus", "(adv.) more, no more", 1),
    ("pouvoir", "pouvoir", "(verb) to be able to, can; (noun [m.]) power", 1),
    ("par", "par", "(prep.) by", 1),
    ("je", "je", "(pron.) I", 1),
    ("avec", "avec", "(prep.) with", 1),
    ("tout", "tout", "(adj., adv., pron., det.) all, very", 1),
    ("faire", "faire", "(verb) to do, make", 1),
    ("son", "son", "(det.) his, her its; (noun [m.]) sound; bran", 1),
    ("mettre", "mettre", "(verb) to put, place", 1),
    ("autre", "autre", "(det., pron.) other", 1),
    ("on", "on", "(pron.) one, we", 1),
    ("mais", "mais", "(conj., adv.) but", 1),
    ("nous", "nous", "(pron.) we, us", 1),
    ("comme", "comme", "(conj., adv.) like, as", 1),
    ("ou", "ou", "(conj.) or", 1),
    ("si", "si", "(conj.) if, whether; (adv.) so", 1),
    ("leur", "leur", "(det., pron.) their, theirs, them", 1),
    ("y", "y", "(adv.) there; (pron.) it", 1),
    ("dire", "dire", "(verb) to say; (noun [m.]) saying", 1),
    ("elle", "elle", "(pron.) she, her", 1),
    ("devoir", "devoir", "(verb) to have to, owe; (noun [m.]) duty", 1),
    ("avant", "avant", "(prep., adv.) before; (noun [m.]) front", 1),
    ("deux", "deux", "(det., noun [m.]) two", 1),
    ("même", "même", "(adj., pron.) same; (adv.) even", 1),
    ("prendre", "prendre", "(verb) to take", 1),
    ("aussi", "aussi", "(adv.) to, also; (conj.) as", 1),
    ("celui", "celui", "(pron.) that, the one, he, him", 1),
    ("donner", "donner", "(verb) to give", 1),
    ("bien", "bien", "(adv.) well; (noun [m.]) good", 1),
    ("où", "où", "(adv., pron.) where", 1),
    ("fois", "fois", "(noun [f.]) time(s)", 1),
    ("vous", "vous", "(pron.) you", 1),
    ("encore", "encore", "(adv.) again, yet", 1),
    ("nouveau", "nouveau", "(adj.) new; (noun [m.]) new (thing)", 1),
    ("aller", "aller", "(verb) to go", 1),
    ("cela", "cela", "(pron.) that, it", 1),
    ("entre", "entre", "(prep.) between", 1),
    ("premier", "premier", "(det., adj.) first", 1),
    ("vouloir", "vouloir", "(verb) to want; (noun [m.]) will, desire", 1),
    ("déjà", "déjà", "(adv.) already", 1),
    ("grand", "grand", "(adj., adv.) great, big, tall", 1),
    ("mon", "mon", "(det.) my", 1),
    ("me", "me", "(pron.) me, to me, myself", 1),
    ("moins", "moins", "(adv.) less; (prep., noun [m.]) minus", 1),
    ("aucun", "aucun", "(det., adj., pron.) none, either, neither, not any", 1),
    ("lui", "lui", "(pron.) him, her", 1),
    ("temps", "temps", "(noun [m.]) time", 1),
    ("très", "très", "(adv.) very", 1),
    ("savoir", "savoir", "(verb) to know; (noun [m.]) learning, knowledge", 1),
    ("falloir", "falloir", "(verb) to take, require, need", 1),
    ("voir", "voir", "(verb) to see", 1),
    ("quelque", "quelque", "(det., adj., adv.) some", 1),
    ("sans", "sans", "(prep.) without", 1),
    ("raison", "raison", "(noun [f.]) reason", 1),
    ("notre", "notre", "(det.) our", 1),
    ("dont", "dont", "(pron.) whose, of which", 1),
    ("non", "non", "(adv.) no, not", 1),
    ("an", "an", "(noun [m.]) year", 1),
    ("monde", "monde", "(noun [m.]) world, people", 1),
    ("jour", "jour", "(noun [m.]) day", 1),
    ("monsieur", "monsieur", "(noun [m.]) mister, sir, gentleman", 1),
    ("demander", "demander", "(verb) to ask for", 1),
    ("alors", "alors", "(adv.) then, so", 1),
    ("après", "après", "(adv., prep.) after", 1),
    ("trouver", "trouver", "(verb) to find", 1),
    ("personne", "personne", "(noun [f.]) person; (pron.) anyone, nobody", 1),
    ("rendre", "rendre", "(verb) to render, return, yield, give up", 1),
    ("part", "part", "(noun [f.]) share", 1),
    ("dernier", "dernier", "(adj). last", 1),
    ("venir", "venir", "(verb) to come", 1),
    ("pendant", "pendant", "(adj.) during; (prep.) for; (noun [m.]) pendant", 1),
    ("passer", "passer", "(verb) to pass", 1),
    ("peu", "peu", "(adv.) little", 1),
    ("lequel", "lequel", "(pron.) who, whom, which", 1),
    ("suite", "suite", "(noun [f.]) result, follow-up, rest", 1),
    ("bon", "bon", "(adj., adv.) good; (noun [m.]) coupon, voucher", 1),
    ("comprendre", "comprendre", "(verb) to understand", 1),
    ("depuis", "depuis", "(prep., adv.) since", 1),
    ("point", "point", "(adv.) at all; (noun [m.]) point", 1),
    ("ainsi", "ainsi", "(adv.) thus", 1),
    ("heure", "heure", "(noun [f.]) hour", 1),
    ("rester", "rester", "(verb) to stay", 1);

