create TABLE meta_info(
   id INTEGER PRIMARY KEY NOT NULL,
   dictionary_name TEXT NOT NULL,
   language_from TEXT NOT NULL,
   language_to TEXT NOT NULL,
   version TEXT NOT NULL
);

create TABLE test_fr_dictionary(
   id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   base_form TEXT NOT NULL,
   base_form_alt TEXT NOT NULL,
   translation TEXT NOT NULL
);

create TABLE test_en_ru_dictionary(
   id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
   base_form TEXT NOT NULL,
   base_form_alt TEXT NOT NULL,
   translation TEXT NOT NULL
);

insert into
    meta_info (id,dictionary_name,language_from,language_to,version)
values
    (1,"test_fr_dictionary","French","English","0.01"),
    (2,"test_en_ru_dictionary","English","Russian","1.0");

insert into
    test_fr_dictionary (base_form,base_form_alt,translation)
values
    ("le", "le", "(det.) the; (pron.) him, her, it, them"),
    ("de", "de", "(det.) some, any; (prep.) of, from"),
    ("un", "un", "(det.) a, an; (adj., pron.) one"),
    ("à ", "à", "(prep.) to, at, in"),
    ("être", "être", "(verb) to be; (noun [m.]) being"),
    ("et", "et", "(conj.) and"),
    ("en", "en", "(prep.) in, by; (adv., pron.)"),
    ("avoir", "avoir", "(verb) to have; (noun [m.]) assets"),
    ("que", "que", "(adv., pron., conj.) that, which, who, whom"),
    ("pour", "pour", "(prep.) for, in order to"),
    ("dans", "dans", "(prep.) in, into, from"),
    ("ce", "ce", "(det., pron.) this, that"),
    ("il", "il", "(pron.) he, it"),
    ("qui", "qui", "(pron.) who, whom"),
    ("ne", "ne", "(adv.) not"),
    ("sur", "sur", "(prep.) on, upon; (adj.) sour"),
    ("se", "se", "(pron.) oneself, himself, herself, itself, themselves"),
    ("pas", "pas", "(adv.) not; (noun [m.]) footstep"),
    ("plus", "plus", "(adv.) more, no more"),
    ("pouvoir", "pouvoir", "(verb) to be able to, can; (noun [m.]) power"),
    ("par", "par", "(prep.) by"),
    ("je", "je", "(pron.) I"),
    ("avec", "avec", "(prep.) with"),
    ("tout", "tout", "(adj., adv., pron., det.) all, very"),
    ("faire", "faire", "(verb) to do, make"),
    ("son", "son", "(det.) his, her its; (noun [m.]) sound; bran"),
    ("mettre", "mettre", "(verb) to put, place"),
    ("autre", "autre", "(det., pron.) other"),
    ("on", "on", "(pron.) one, we"),
    ("mais", "mais", "(conj., adv.) but"),
    ("nous", "nous", "(pron.) we, us"),
    ("comme", "comme", "(conj., adv.) like, as"),
    ("ou", "ou", "(conj.) or"),
    ("si", "si", "(conj.) if, whether; (adv.) so"),
    ("leur", "leur", "(det., pron.) their, theirs, them"),
    ("y", "y", "(adv.) there; (pron.) it"),
    ("dire", "dire", "(verb) to say; (noun [m.]) saying"),
    ("elle", "elle", "(pron.) she, her"),
    ("devoir", "devoir", "(verb) to have to, owe; (noun [m.]) duty"),
    ("avant", "avant", "(prep., adv.) before; (noun [m.]) front"),
    ("deux", "deux", "(det., noun [m.]) two"),
    ("même", "même", "(adj., pron.) same; (adv.) even"),
    ("prendre", "prendre", "(verb) to take"),
    ("aussi", "aussi", "(adv.) to, also; (conj.) as"),
    ("celui", "celui", "(pron.) that, the one, he, him"),
    ("donner", "donner", "(verb) to give"),
    ("bien", "bien", "(adv.) well; (noun [m.]) good"),
    ("où", "où", "(adv., pron.) where"),
    ("fois", "fois", "(noun [f.]) time(s)"),
    ("vous", "vous", "(pron.) you"),
    ("encore", "encore", "(adv.) again, yet"),
    ("nouveau", "nouveau", "(adj.) new; (noun [m.]) new (thing)"),
    ("aller", "aller", "(verb) to go"),
    ("cela", "cela", "(pron.) that, it"),
    ("entre", "entre", "(prep.) between"),
    ("premier", "premier", "(det., adj.) first"),
    ("vouloir", "vouloir", "(verb) to want; (noun [m.]) will, desire"),
    ("déjà", "déjà", "(adv.) already"),
    ("grand", "grand", "(adj., adv.) great, big, tall"),
    ("mon", "mon", "(det.) my"),
    ("me", "me", "(pron.) me, to me, myself"),
    ("moins", "moins", "(adv.) less; (prep., noun [m.]) minus"),
    ("aucun", "aucun", "(det., adj., pron.) none, either, neither, not any"),
    ("lui", "lui", "(pron.) him, her"),
    ("temps", "temps", "(noun [m.]) time"),
    ("très", "très", "(adv.) very"),
    ("savoir", "savoir", "(verb) to know; (noun [m.]) learning, knowledge"),
    ("falloir", "falloir", "(verb) to take, require, need"),
    ("voir", "voir", "(verb) to see"),
    ("quelque", "quelque", "(det., adj., adv.) some"),
    ("sans", "sans", "(prep.) without"),
    ("raison", "raison", "(noun [f.]) reason"),
    ("notre", "notre", "(det.) our"),
    ("dont", "dont", "(pron.) whose, of which"),
    ("non", "non", "(adv.) no, not"),
    ("an", "an", "(noun [m.]) year"),
    ("monde", "monde", "(noun [m.]) world, people"),
    ("jour", "jour", "(noun [m.]) day"),
    ("monsieur", "monsieur", "(noun [m.]) mister, sir, gentleman"),
    ("demander", "demander", "(verb) to ask for"),
    ("alors", "alors", "(adv.) then, so"),
    ("après", "après", "(adv., prep.) after"),
    ("trouver", "trouver", "(verb) to find"),
    ("personne", "personne", "(noun [f.]) person; (pron.) anyone, nobody"),
    ("rendre", "rendre", "(verb) to render, return, yield, give up"),
    ("part", "part", "(noun [f.]) share"),
    ("dernier", "dernier", "(adj). last"),
    ("venir", "venir", "(verb) to come"),
    ("pendant", "pendant", "(adj.) during; (prep.) for; (noun [m.]) pendant"),
    ("passer", "passer", "(verb) to pass"),
    ("peu", "peu", "(adv.) little"),
    ("lequel", "lequel", "(pron.) who, whom, which"),
    ("suite", "suite", "(noun [f.]) result, follow-up, rest"),
    ("bon", "bon", "(adj., adv.) good; (noun [m.]) coupon, voucher"),
    ("comprendre", "comprendre", "(verb) to understand"),
    ("depuis", "depuis", "(prep., adv.) since"),
    ("point", "point", "(adv.) at all; (noun [m.]) point"),
    ("ainsi", "ainsi", "(adv.) thus"),
    ("heure", "heure", "(noun [f.]) hour"),
    ("rester", "rester", "(verb) to stay");

insert into
    test_en_ru_dictionary (base_form,base_form_alt,translation)
values
    ("as", "as", "as [ æ z ] — как"),
    ("I", "I", "I [ a ɪ ] — я"),
    ("his", "his", "his [ hɪz ] — его"),
    ("that", "that", "that [ ðæt ] — что / тот"),
    ("he", "he", "he [ hi ː ] — он"),
    ("was", "was", "was [ wɒz ] — был"),
    ("for", "for", "for [ fɔː r ] — для"),
    ("on", "on", "on [ ɒ n ] — на"),
    ("are", "are", "are [ ɑː r ] — являются"),
    ("with", "with", "with [ wɪð ] — с"),
    ("they", "they", "they [ ð e ɪ ] — они"),
    ("be", "be", "be [ bi ː ] — быть"),
    ("at", "at", "at [ ə t ] — на"),
    ("one", "one", "one [ wʌn ] — один"),
    ("have", "have", "have [ hæv ] — иметь"),
    ("this", "this", "this [ ðɪs ] — это"),
    ("from", "from", "from [ frɒm ] — из"),
    ("by", "by", "by [ ba ɪ ] — от"),
    ("hot", "hot", "hot [ hɒt ] — горячий / жарко"),
    ("word", "word", "word [ wɜːd ] — слово"),
    ("but", "but", "but [ bʌt ] — но"),
    ("what", "what", "what [ wɒt ] — что"),
    ("some", "some", "some [ sʌm ] — некоторый"),
    ("is", "is", "is [ ɪ z ] — является"),
    ("it", "it", "it [ ɪ t ] — это"),
    ("you", "you", "you [ ju ː ] — ты"),
    ("or", "or", "or [ ɔː r ] — или"),
    ("had", "had", "had [ hæd ] — имел"),
    ("the", "the", "the [ ð i ː ]"),
    ("of", "of", "of [ ə v ] — из / о"),
    ("to", "to", "to [ tu ː ] — в / к"),
    ("and", "and", "and [ æ nd ] — и"),
    ("a", "a", "a [ ə ]"),
    ("in", "in", "in [ ɪ n ] — в"),
    ("we", "we", "we [ wi ː ] — мы"),
    ("can", "can", "can [ kæn ] — может"),
    ("out", "out", "out [ aʊt ] — из / вне"),
    ("other", "other", "other [ ˈʌð.ə r ] — другой"),
    ("were", "were", "were [ wɜː r ] — были"),
    ("which", "which", "which [ wɪtʃ ] — который"),
    ("do", "do", "do [ du ː ] — делать"),
    ("their", "their", "their [ ð e ə r ] — их"),
    ("time", "time", "time [ taɪm ] — время"),
    ("if", "if", "if [ ɪ f ] — если"),
    ("will", "will", "will [wɪl] — будет"),
    ("how", "how", "how [ ha ʊ ] — как"),
    ("said", "said", "said [ sed ] — говорить"),
    ("an", "an", "an [ æ n ]"),
    ("each", "each", "each [ iːtʃ ] — каждый"),
    ("tell", "tell", "tell [ tel ] — говорить"),
    ("does", "does", "does [ dʌz ] — делает"),
    ("set", "set", "set [ set ] — задавать / комплект"),
    ("three", "three", "three [ θ ri ː ] — три"),
    ("want", "want", "want [ wɒnt ] — хотеть"),
    ("air", "air", "air [ e ə r ] — воздух"),
    ("well", "well", "well [ wel ] — хорошо"),
    ("also", "also", "also [ ˈɔːl. səʊ ] — также"),
    ("play", "play", "play [ ple ɪ ] — играть"),
    ("small", "small", "small [ smɔːl ] — маленький"),
    ("end", "end", "end [ end ] — конец"),
    ("put", "put", "put [ pʊt ] — ставить"),
    ("home", "home", "home [ həʊm ] — дом"),
    ("read", "read", "read [ riːd ] — читать"),
    ("hand", "hand", "hand [ hænd ] — рука"),
    ("port", "port", "port [ pɔːt ] — порт"),
    ("large", "large", "large [ lɑːdʒ ] — большой"),
    ("spell", "spell", "spell [ spel ] — читать по буквам / орфография"),
    ("add", "add", "add [ æ d ] — добавлять"),
    ("even", "even", "even [ ˈiː.v ə n ] — даже"),
    ("land", "land", "land [ lænd ] — земля"),
    ("here", "here", "here [ hɪə r ] — здесь"),
    ("must", "must", "must [ mʌst ] — должен"),
    ("big", "big", "big [ bɪɡ ] — большой"),
    ("high", "high", "high [ ha ɪ ] — высокий"),
    ("such", "such", "such [ sʌtʃ ] — такой"),
    ("follow", "follow", "follow [ ˈfɒl.əʊ ] — следовать"),
    ("act", "act", "act [ æ kt ] — действовать"),
    ("why", "why", "why [ wa ɪ ] — почему"),
    ("ask", "ask", "ask [ ɑːsk ] — спрашивать"),
    ("men", "men", "men [ men ] — люди"),
    ("change", "change", "change [ tʃeɪndʒ ] — менять"),
    ("went", "went", "went [ went ] — отправился"),
    ("light", "light", "light [ laɪt ] — свет / легкий"),
    ("kind", "kind", "kind [ kaɪnd ] — добрый / разновидность"),
    ("off", "off", "off [ ɒ f ] — от / выключенный"),
    ("need", "need", "need [ niːd ] — необходимость"),
    ("house", "house", "house [ haʊs ] — дом"),
    ("picture", "picture", "picture [ ˈpɪk. tʃə r ] — картина / фото"),
    ("try", "try", "try [ tra ɪ ] — пробовать / пытаться"),
    ("us", "us", "us [ ʌ s ] — нас"),
    ("again", "again", "again [ əˈɡen ] — снова"),
    ("animal", "animal", "animal [ ˈæn.ɪ.məl ] — животное"),
    ("point", "point", "point [ pɔɪnt ] — точка"),
    ("mother", "mother", "mother [ ˈmʌð.ə r ] — мать"),
    ("world", "world", "world [ wɜːld ] — мир"),
    ("near", "near", "near [ nɪə r ] — близко"),
    ("build", "build", "build [ bɪld ] — строить"),
    ("self", "self", "self [ self ] — себя"),
    ("earth", "earth", "earth [ ɜːθ ] — земля"),
    ("father", "father", "father [ ˈfɑː.ðə r ] — отец"),
    ("any", "any", "any [ ˈ en. i ] — любой"),
    ("new", "new", "new [ nju ː ] — новый"),
    ("work", "work", "work [ wɜːk ] — работа"),
    ("part", "part", "part [pɑːt] — часть"),
    ("take", "take", "take [ teɪk ] — брать"),
    ("get", "get", "get [ get ] — получать"),
    ("place", "place", "place [ pleɪs ] — место"),
    ("made", "made", "made [ meɪd ] — сделать"),
    ("live", "live", "live [ lɪv ] — жить"),
    ("where", "where", "where [ we ə r ] — где"),
    ("after", "after", "after [ ˈɑːf. t ə r ] — после"),
    ("back", "back", "back [ bæk ] — назад"),
    ("little", "little", "little [ˈlɪt.əl] — немного"),
    ("only", "only", "only [ ˈəʊn. li ] — только"),
    ("round", "round", "round [ raʊnd ] — круглый / вокруг"),
    ("man", "man", "man [ mæn ] — мужчина"),
    ("year", "year", "year [ jɪə r ] — год"),
    ("came", "came", "came [ keɪm ] — пришел"),
    ("show", "show", "show [ ʃəʊ ] — показывать"),
    ("every", "every", "every [ ˈ ev. ri ] — каждый"),
    ("good", "good", "good [ ɡʊd ] — хороший"),
    ("me", "me", "me [ mi ː ] — мне"),
    ("give", "give", "give [ ɡɪv ] — давать"),
    ("our", "our", "our [ aʊə r ] — наш"),
    ("under", "under", "under [ ˈʌn. d ə r ] — под"),
    ("name", "name", "name [ neɪm ] — имя"),
    ("very", "very", "very [ ˈ ver. i ] — очень"),
    ("through", "through", "through [ θ ru ː ] — через"),
    ("just", "just", "just [ dʒʌst ] — только / просто"),
    ("form", "form", "form [ fɔːm ] — вид, форма / образовывать"),
    ("sentence", "sentence", "sentence [ ˈ sen. təns ] — предложение"),
    ("great", "great", "great [ ɡreɪt ] — отличный"),
    ("think", "think", "think [ θɪŋk ] — думать"),
    ("say", "say", "say [ se ɪ ] — говорить"),
    ("help", "help", "help [ help ] — помогать, помощь"),
    ("low", "low", "low [ ləʊ] — низкий"),
    ("line", "line", "line [ laɪn ] — линия, черта"),
    ("differ", "differ", "differ [ ˈdɪf.ə r ] — отличаться"),
    ("turn", "turn", "turn [ tɜːn ] — поворачивать"),
    ("cause", "cause", "cause [ kɔːz ] — причина"),
    ("much", "much", "much [ mʌtʃ ] — много"),
    ("mean", "mean", "mean [miːn] — значить / подлый / средний"),
    ("before", "before", "before [ bɪˈfɔː r ] — до"),
    ("move", "move", "move [ muːv ] — двигать"),
    ("right", "right", "right [ raɪt ] — право / верный"),
    ("boy", "boy", "boy [ bɔɪ ] — мальчик"),
    ("old", "old", "old [ əʊld ] — старый"),
    ("too", "too", "too [ tu ː ] — тоже"),
    ("same", "same", "same [ seɪm ] — также"),
    ("she", "she", "she [ ʃ i ː ] — она"),
    ("all", "all", "all [ ɔːl ] — все"),
    ("there", "there", "there [ ð e ə r ] — там"),
    ("when", "when", "when [ wen ] — когда"),
    ("up", "up", "up [ ʌ p ] — вверх / подниматься"),
    ("use", "use", "use [ juːz ] — использовать"),
    ("your", "your", "your [ jɔː r ] — твой"),
    ("way", "way", "way [ we ɪ ] — путь"),
    ("about", "about", "about [ əˈbaʊt ] — о"),
    ("many", "many", "many [ ˈ men. i ] — много"),
    ("then", "then", "then [ ð en ] — затем"),
    ("them", "them", "them [ ð em ] — их"),
    ("write", "write", "write [ raɪt ] — писать"),
    ("would", "would", "would [ wʊd ] — бы / было бы"),
    ("like", "like", "like [ laɪk ] — нравиться"),
    ("so", "so", "so [ səʊ ] — так"),
    ("these", "these", "these [ ðiːz ] — эти"),
    ("her", "her", "her [ hɜː r ] — ее"),
    ("long", "long", "long [ lɒŋ ] — долго / длинный"),
    ("make", "make", "make [ meɪk ] — делать"),
    ("thing", "thing", "thing [ θɪŋ ] — вещь"),
    ("see", "see", "see [ si ː ] — видеть"),
    ("him", "him", "him [ hɪm ] — его"),
    ("two", "two", "two [ tu ː ] — два / двое"),
    ("has", "has", "has [ hæz ] — имеет"),
    ("look", "look", "look [ lʊk ] — смотреть / взгляд"),
    ("more", "more", "more [ mɔː r ] — больше"),
    ("day", "day", "day [ de ɪ ] — день"),
    ("could", "could", "could [ kʊd ] — мог"),
    ("go", "go", "go [ ɡəʊ ] — идти"),
    ("come", "come", "come [ kʌm ] — приходить"),
    ("did", "did", "did [ dɪd ] — сделал"),
    ("number", "number", "number [ ˈnʌm. b ə r ] — номер"),
    ("sound", "sound", "sound [ saʊnd ] — звук"),
    ("no", "no", "no [ nəʊ ] — нет"),
    ("most", "most", "most [ məʊst ] — самый / большинство"),
    ("people", "people", "people [ ˈpiː.p ə l ] — люди"),
    ("my", "my", "my [ ma ɪ ] — мой"),
    ("over", "over", "over [ ˈəʊ.və r ] — над"),
    ("know", "know", "know [ nəʊ ] — знать"),
    ("water", "water", "water [ ˈwɔː.tə r ] — вода"),
    ("than", "than", "than [ ðæn ] — чем"),
    ("call", "call", "call [ kɔːl ] — звонить / звонок"),
    ("first", "first", "first [ ˈfɜːst ] — первый"),
    ("who", "who", "who [ hu ː ] — кто"),
    ("may", "may", "may [ me ɪ ] — может"),
    ("down", "down", "down [ daʊn ] — вниз"),
    ("side", "side", "side [ saɪd ] — сторона"),
    ("been", "been", "been [ biːn ] — был"),
    ("now", "now", "now [ na ʊ ] — сейчас"),
    ("find", "find", "find [ faɪnd ] — найти"),
    ("head", "head", "head [ hed ] — голова"),
    ("stand", "stand", "stand [stænd] — стоять"),
    ("own", "own", "own [ əʊn ] — свой / владеть"),
    ("page", "page", "page [ peɪdʒ ] — страница"),
    ("should", "should", "should [ ʃʊd ] — должен"),
    ("country", "country", "country [ ˈkʌn. tri ] — страна"),
    ("found", "found", "found [ faʊnd ] — найденный"),
    ("answer", "answer", "answer [ ˈæn·sər ] — ответ / отвечать"),
    ("school", "school", "school [ skuːl ] — школа"),
    ("grow", "grow", "grow [ ɡrəʊ ] — расти"),
    ("study", "study", "study [ ˈstʌd. i ] — изучать"),
    ("still", "still", "still [ stɪl ] — все еще"),
    ("learn", "learn", "learn [ lɜːn ] — учиться"),
    ("plant", "plant", "plant [ plɑːnt ] — растение / сажать"),
    ("cover", "cover", "cover [ ˈkʌv.ə r ] — накрывать / обложка"),
    ("food", "food", "food [ fuːd ] — еда"),
    ("sun", "sun", "sun [ sʌn ] — солнце"),
    ("four", "four", "four [ fɔː r ] — четыре"),
    ("between", "between", "between [ bɪˈtwiːn ] — между"),
    ("state", "state", "state [ steɪt ] — состояние, государство, штат"),
    ("keep", "keep", "keep [ kiːp ] — держать, продолжать"),
    ("eye", "eye", "eye [ a ɪ ] — глаз"),
    ("never", "never", "never [ ˈnev.ə r ] — никогда"),
    ("last", "last", "last [ lɑːst ] — последний"),
    ("let", "let", "let [ let ] — позволять"),
    ("thought", "thought", "thought [ θɔːt ] — мысль / думал"),
    ("city", "city", "city [ ˈsɪt. i ] — город"),
    ("tree", "tree", "tree [ tri ː ] — дерево"),
    ("cross", "cross", "cross [ krɒs ] — пересекать / крест"),
    ("farm", "farm", "farm [ fɑːm ] — ферма"),
    ("hard", "hard", "hard [ hɑːd ] — тяжелый / твердый"),
    ("start", "start", "start [ stɑːt ] — начинать"),
    ("might", "might", "might [ maɪt ] — может быть / мощь"),
    ("story", "story", "story [ ˈstɔː.ri ] — история"),
    ("saw", "saw", "saw [ sɔː ] — увидел / пила"),
    ("far", "far", "far [ fɑː r ] — далеко"),
    ("sea", "sea", "sea [ si ː ] — море"),
    ("draw", "draw", "draw [ drɔː ] — рисовать"),
    ("left", "left", "left [ left ] — лево / оставил"),
    ("late", "late", "late [ leɪt ] — поздно"),
    ("run", "run", "run [ rʌn ] — бежать"),
    ("don’t", "don’t", "don’t [ dəʊnt ] — не"),
    ("while", "while", "while [ waɪl ] — в то время, как"),
    ("press", "press", "press [ pres ] — нажимать / давить"),
    ("close", "close", "close [ kləʊz ] — близко / закрывать"),
    ("night", "night", "night [ naɪt ] — ночь"),
    ("real", "real", "real [ rɪəl ] — реальный"),
    ("life", "life", "life [ laɪf ] — жизнь"),
    ("few", "few", "few [ fju ː ] — несколько"),
    ("north", "north", "north [ nɔːθ ] — север"),
    ("book", "book", "book [ bʊk ] — книга"),
    ("carry", "carry", "carry [ ˈkær. i ] — нести"),
    ("took", "took", "took [ tʊk ] — взял"),
    ("science", "science", "science [ ˈsaɪ.əns ] — наука"),
    ("eat", "eat", "eat [ iːt ] — есть"),
    ("room", "room", "room [ ruːm ] — комната"),
    ("friend", "friend", "friend [ frend ] — друг"),
    ("began", "began", "began [ bɪˈɡæn ] — началось"),
    ("idea", "idea", "idea [ aɪˈdɪə ] — идея"),
    ("fish", "fish", "fish [ fɪʃ ] — рыба"),
    ("mountain", "mountain", "mountain [ ˈmaʊn. tɪn ] — гора"),
    ("stop", "stop", "stop [ stɒp ] — остановка / останавливать"),
    ("once", "once", "once [ wʌns ] — однажды"),
    ("base", "base", "base [ beɪs ] — базовый / основывать"),
    ("hear", "hear", "hear [ hɪə r ] — слышать"),
    ("horse", "horse", "horse [ hɔːs ] — лошадь"),
    ("cut", "cut", "cut [ kʌt ] — резать"),
    ("sure", "sure", "sure [ ʃɔː r ] — конечно / уверен"),
    ("watch", "watch", "watch [ wɒtʃ ] — смотреть / часы"),
    ("colour", "colour", "colour [ ˈkʌl.ə r ] — цвет"),
    ("face", "face", "face [ feɪs ] — лицо"),
    ("wood", "wood", "wood [ wʊd ] — дерево"),
    ("main", "main", "main [ meɪn ] — главный"),
    ("open", "open", "open [ ˈəʊ.p ə n ] — открыть"),
    ("seem", "seem", "seem [ siːm ] — казаться"),
    ("together", "together", "together [ təˈɡeð.ə r ] — вместе"),
    ("next", "next", "next [ nekst ] — следующий"),
    ("white", "white", "white [ waɪt ] — белый"),
    ("children", "children", "children [ ˈtʃɪl. drən ] — дети"),
    ("begin", "begin", "begin [ bɪˈɡɪn ] — начинать"),
    ("got", "got", "got [ ɡɒt ] — получил"),
    ("walk", "walk", "walk [ wɔːk ] — гулять / прогулка"),
    ("example", "example", "example [ ɪɡˈzɑːm. p ə l ] — пример"),
    ("ease", "ease", "ease [ iːz ] — легкость / облегчать"),
    ("paper", "paper", "paper [ ˈpeɪ.pə r ] — бумага"),
    ("group", "group", "group [ ɡruːp ] — группа"),
    ("always", "always", "always [ ˈɔːl. weɪz ] — всегда"),
    ("music", "music", "music [ ˈmjuː.zɪk ] — музыка"),
    ("those", "those", "those [ ðəʊz ] — те"),
    ("both", "both", "both [ bəʊθ ] — оба"),
    ("mark", "mark", "mark [ mɑːk ] — отметка / отмечать"),
    ("often", "often", "often [ ˈɒf. ə n ] — часто"),
    ("letter", "letter", "letter [ ˈlet.ə r ] — письмо"),
    ("until", "until", "until [ ənˈtɪl ] — до тех пор"),
    ("mile", "mile", "mile [ maɪl ] — миля"),
    ("river", "river", "river [ ˈrɪv.ə r ] — река"),
    ("car", "car", "car [ kɑː r ] — машина"),
    ("feet", "feet", "feet [ fiːt ] — ноги"),
    ("care", "care", "care [ ke ə r ] — заботиться / уход"),
    ("second", "second", "second [ ˈ sek. ə nd ] — секунда"),
    ("enough", "enough", "enough [ ɪˈnʌf ] — достаточно / довольно"),
    ("plain", "plain", "plain [ pleɪn ] — простой"),
    ("girl", "girl", "girl [ ɡɜːl ] — девочка"),
    ("usual", "usual", "usual [ ˈjuː.ʒu.əl ] — обычно"),
    ("young", "young", "young [ jʌŋ ] — молодой"),
    ("ready", "ready", "ready [ ˈ red. i ] — готовый"),
    ("above", "above", "above [ əˈbʌv ] — выше"),
    ("ever", "ever", "ever [ ˈev.ə r ] — когда-либо"),
    ("red", "red", "red [ red ] — красный"),
    ("list", "list", "list [ lɪst ] — список"),
    ("though", "though", "though [ ðəʊ ] — хоть"),
    ("feel", "feel", "feel [ fiːl ] — чувствовать"),
    ("talk", "talk", "talk [ tɔːk ] — говорить"),
    ("bird", "bird", "bird [ bɜːd ] — птица"),
    ("soon", "soon", "soon [ suːn ] — скоро"),
    ("body", "body", "body [ ˈbɒd. i ] — тело"),
    ("dog", "dog", "dog [ dɒɡ ] — собака"),
    ("family", "family", "family [ ˈfæm. ə l. i ] — семья"),
    ("direct", "direct", "direct [ daɪˈrekt ] — непосредственный / направлять"),
    ("pose", "pose", "pose [ pəʊz ] — поза / позировать"),
    ("leave", "leave", "leave [ liːv ] — покидать"),
    ("song", "song", "song [ sɒŋ ] — песня"),
    ("measure", "measure", "measure [ ˈmeʒ.ə r ] — мера / измерять"),
    ("door", "door", "door [ dɔː r ] — дверь"),
    ("product", "product", "product [ ˈprɒd.ʌkt ] — продукт"),
    ("black", "black", "black [ blæk ] — черный"),
    ("short", "short", "short [ ʃɔːt ] — короткий"),
    ("numeral", "numeral", "numeral [ ˈnjuː.mə.rəl ] — числительное"),
    ("class", "class", "class [ klɑːs ] — класс / сорт"),
    ("wind", "wind", "wind [ wɪnd ] — ветер"),
    ("question", "question", "question [ ˈ kwes. tʃən ] — вопрос"),
    ("happen", "happen", "happen [ ˈhæp. ə n ] — случаться"),
    ("complete", "complete", "complete [ kəmˈpliːt ] — полный / завершенный"),
    ("ship", "ship", "ship [ʃɪp] — корабль"),
    ("area", "area", "area [ ˈeə.ri.ə ] — площадь / зона"),
    ("half", "half", "half [ hɑːf ] — половина"),
    ("rock", "rock", "rock [ rɒk ] — рок / камень / скала"),
    ("order", "order", "order [ ˈɔː.də r ] — заказ / порядок"),
    ("fire", "fire", "fire [faɪər]— огонь"),
    ("south", "south", "south [ saʊθ ] — юг"),
    ("problem", "problem", "problem [ ˈprɒb. ləm ] — проблема"),
    ("piece", "piece", "piece [ piːs ] — часть / кусок"),
    ("told", "told", "told [ təʊld ] — говорил"),
    ("knew", "knew", "knew [ nju ː ] — знал"),
    ("pass", "pass", "pass [ pɑːs ] — проходить / передача"),
    ("since", "since", "since [ sɪns ] — с / поскольку"),
    ("top", "top", "top [ tɒp ] — верх / вершина"),
    ("whole", "whole", "whole [ həʊl ] — весь / целый"),
    ("king", "king", "king [ kɪŋ ] — король"),
    ("street", "street", "street [ striːt ] — улица"),
    ("inch", "inch", "inch [ ɪ nt ʃ ] — дюйм"),
    ("multiply", "multiply", "multiply [ ˈmʌl. t ɪ. pla ɪ ] — умножать"),
    ("nothing", "nothing", "nothing [ ˈnʌθ.ɪŋ ] — ничего"),
    ("course", "course", "course [ kɔːs ] — курс / блюдо"),
    ("stay", "stay", "stay [ ste ɪ ] — оставаться"),
    ("wheel", "wheel", "wheel [ wiːl ] — колесо"),
    ("full", "full", "full [ fʊl ] — полный"),
    ("force", "force", "force [ fɔːs ] — сила / заставлять"),
    ("blue", "blue", "blue [ blu ː ] — голубой / синий / грустный"),
    ("object", "object", "object [ ˈɒb. dʒɪkt ] — объект"),
    ("decide", "decide", "decide [ dɪˈsaɪd ] — решать"),
    ("surface", "surface", "surface [ ˈsɜː.fɪs ] — поверхность"),
    ("deep", "deep", "deep [ diːp ] — глубоко"),
    ("moon", "moon", "moon [ muːn ] — луна"),
    ("island", "island", "island [ ˈaɪ.lənd ] — остров"),
    ("foot", "foot", "foot [ fʊt ] — нога"),
    ("system", "system", "system [ ˈsɪs. təm ] — система"),
    ("busy", "busy", "busy [ ˈbɪz. i ] — занят"),
    ("test", "test", "test [ test ] — тест / проверять"),
    ("record", "record", "record [ rɪˈkɔːd ] — записывать"),
    ("boat", "boat", "boat [ bəʊt ] — лодка"),
    ("common", "common", "common [ ˈkɒm.ən ] — общий / обычный"),
    ("gold", "gold", "gold [ ɡəʊld ] — золото"),
    ("possible", "possible", "possible [ ˈpɒs.ə.b ə l ] — возможный"),
    ("plane", "plane", "plane [ pleɪn ] — самолет / плоскость"),
    ("stead", "stead", "stead [ sted ] — место"),
    ("dry", "dry", "dry [ dra ɪ ] — сухой"),
    ("wonder", "wonder", "wonder [ ˈwʌn. d ə r ] — чудо / удивляться"),
    ("laugh", "laugh", "laugh [ lɑːf ] — смех / смеяться"),
    ("thousand", "thousand", "thousand [ ˈθaʊ.z ə nd ] — тысяча"),
    ("ago", "ago", "ago [ əˈɡəʊ ] — тому назад"),
    ("ran", "ran", "ran [ ræn ] — побежал"),
    ("check", "check", "check [ tʃek ] — проверять"),
    ("game", "game", "game [ ɡeɪm ] — игра"),
    ("shape", "shape", "shape [ ʃeɪp ] — форма"),
    ("equate", "equate", "equate [ ɪˈkweɪt ] — приравнивать"),
    ("OK", "OK", "OK [ ˌəʊˈkeɪ ] — хорошо"),
    ("miss", "miss", "miss [ mɪs ] — скучать / пропускать"),
    ("brought", "brought", "brought [ brɔːt ] — привел"),
    ("heat", "heat", "heat [ hiːt ] — жара, высокая температура"),
    ("snow", "snow", "snow [ snəʊ ] — снег"),
    ("tire", "tire", "tire [ taɪə r ] — шина / утомлять"),
    ("bring", "bring", "bring [ brɪŋ ] — приносить"),
    ("yes", "yes", "yes [ jes ] — да"),
    ("distant", "distant", "distant [ ˈdɪs. t ə nt ] — отдаленный"),
    ("fill", "fill", "fill [ fɪl ] — наполнять"),
    ("east", "east", "east [ iːst ] — восток"),
    ("paint", "paint", "paint [ peɪnt ] — краска / красить"),
    ("language", "language", "language [ ˈlæŋ.ɡwɪdʒ ] — язык"),
    ("among", "among", "among [ əˈmʌŋ ] — среди"),
    ("unit", "unit", "unit [ ˈjuː.nɪt ] — единица"),
    ("power", "power", "power [ paʊə r ] — мощность / сила"),
    ("town", "town", "town [ taʊn ] — город"),
    ("fine", "fine", "fine [ faɪn ] — отлично"),
    ("certain", "certain", "certain [ ˈsɜː.t ə n ] — определенный"),
    ("fly", "fly", "fly [ fla ɪ ] — летать"),
    ("fall", "fall", "fall [fɔːl] — падать / осень"),
    ("lead", "lead", "lead [ liːd ] — вести / руководить"),
    ("cry", "cry", "cry [ kra ɪ ] — плакать"),
    ("dark", "dark", "dark [ dɑːk ] — темный, темнота"),
    ("machine", "machine", "machine [ məˈʃiːn ] — машина / механизм"),
    ("note", "note", "note [ nəʊt ] — примечание / отмечать"),
    ("wait", "wait", "wait [ weɪt ] — ждать"),
    ("plan", "plan", "plan [ plæn ] — план"),
    ("figure", "figure", "figure [ ˈfɪɡ.ə r ] — цифра / фигура"),
    ("star", "star", "star [ stɑː r ] — звезда"),
    ("box", "box", "box [ bɒks ] — коробка"),
    ("noun", "noun", "noun [ naʊn ] — существительное"),
    ("field", "field", "field [ fiːld ] — поле"),
    ("rest", "rest", "rest [ rest ] — остальное / отдыхать"),
    ("correct", "correct", "correct [ kəˈrekt ] — поправлять / правильный"),
    ("able", "able", "able [ ˈeɪ.b ə l ] — в состоянии / способный"),
    ("pound", "pound", "pound [ paʊnd ] — фунт"),
    ("done", "done", "done [ dʌn ] — сделанный"),
    ("beauty", "beauty", "beauty [ ˈbjuː.ti ] — красота"),
    ("drive", "drive", "drive [ draɪv ] — водить"),
    ("stood", "stood", "stood [ stʊd ] — стоял"),
    ("contain", "contain", "contain [ kənˈteɪn ] — содержать"),
    ("front", "front", "front [ frʌnt ] — перед"),
    ("teach", "teach", "teach [tiːtʃ] — обучать"),
    ("week", "week", "week [ wiːk ] — неделя"),
    ("final", "final", "final [ ˈfaɪ.n ə l ] — финал / последний"),
    ("gave", "gave", "gave [ ɡeɪv ] — дал"),
    ("green", "green", "green [ ɡriːn ] — зеленый"),
    ("oh", "oh", "oh [ əʊ ] — ох"),
    ("quick", "quick", "quick [ kwɪk ] — быстро"),
    ("develop", "develop", "develop [ dɪˈvel.əp ] — развивать"),
    ("ocean", "ocean", "ocean [ ˈəʊ.ʃ ə n ] — океан"),
    ("warm", "warm", "warm [ wɔːm ] — тепло"),
    ("free", "free", "free [ fri ː ] — свободный"),
    ("minute", "minute", "minute [ ˈmɪn.ɪt ] — минута"),
    ("strong", "strong", "strong [ strɒŋ ] — сильный"),
    ("special", "special", "special [ˈspeʃ.əl] — особый"),
    ("mind", "mind", "mind [ maɪnd ] — разум / возражать"),
    ("behind", "behind", "behind [ bɪˈhaɪnd ] — позади"),
    ("clear", "clear", "clear [ klɪə r ] — ясный / понятно"),
    ("tail", "tail", "tail [ teɪl ] — хвост"),
    ("produce", "produce", "produce [ prəˈdʒuːs ] — производить"),
    ("fact", "fact", "fact [ fækt ] — факт"),
    ("space", "space", "space [ speɪs ] — пространство / космос"),
    ("heard", "heard", "heard [ h ɜːd ] — слышал"),
    ("best", "best", "best [ best ] — лучший"),
    ("hour", "hour", "hour [ aʊə r ] — час"),
    ("better", "better", "better [ ˈbet.ə r ] — лучше"),
    ("true", "true", "true [ tru ː ] — правда"),
    ("during", "during", "during [ ˈdʒʊə.rɪŋ ] — в течение"),
    ("hundred", "hundred", "hundred [ ˈhʌn. drəd ] — сотня"),
    ("five", "five", "five [ faɪv ] — пять"),
    ("remember", "remember", "remember [ rɪˈmem. b ə r ] — помнить"),
    ("step", "step", "step [ step ] — шаг"),
    ("early", "early", "early [ ˈɜː.li ] — ранний / рано"),
    ("hold", "hold", "hold [ həʊld ] — держать"),
    ("west", "west", "west [ west ] — запад"),
    ("ground", "ground", "ground [ ɡraʊnd ] — земля"),
    ("interest", "interest", "interest [ ˈɪn. trəst ] — интерес"),
    ("reach", "reach", "reach [ riːtʃ ] — достигать"),
    ("fast", "fast", "fast [ fɑːst ] — быстро"),
    ("verb", "verb", "verb [ vɜːb ] — глагол"),
    ("sing", "sing", "sing [ sɪŋ ] — петь"),
    ("listen", "listen", "listen [ ˈlɪs. ə n ] — слушать"),
    ("six", "six", "six [ sɪks ] — шесть"),
    ("table", "table", "table [ ˈteɪ.b ə l ] — стол"),
    ("travel", "travel", "travel [ ˈtræv. ə l ] — путешествовать"),
    ("less", "less", "less [ les ] — меньше"),
    ("morning", "morning", "morning [ ˈmɔː.nɪŋ ] — утро"),
    ("ten", "ten", "ten [ ten ] — десять"),
    ("simple", "simple", "simple [ ˈsɪm. p ə l ] — просто / простой"),
    ("several", "several", "several [ ˈ sev. ə r. ə l ] — несколько"),
    ("vowel", "vowel", "vowel [ vaʊəl ] — гласный (звук)"),
    ("towards", "towards", "towards [ twoʊrdz ] — к / по направлению к"),
    ("war", "war", "war [ wɔː r ] — война"),
    ("lay", "lay", "lay [ le ɪ ] — лежать"),
    ("against", "against", "against [ əˈɡenst ] — против"),
    ("pattern", "pattern", "pattern [ ˈpæt. ə n ] — узор"),
    ("slow", "slow", "slow [ sləʊ ] — медленно / медленный"),
    ("center", "center", "center [ ˈ sen. t ə r ] — центр"),
    ("love", "love", "love [ lʌv ] — любовь"),
    ("person", "person", "person [ ˈpɜː.s ə n ] — человек"),
    ("money", "money", "money [ ˈmʌn. i ] — деньги"),
    ("serve", "serve", "serve [ sɜːv ] — обслуживать"),
    ("appear", "appear", "appear [ əˈpɪə r ] — появляться"),
    ("road", "road", "road [ rəʊd ] — дорога"),
    ("map", "map", "map [ mæp ] — карта"),
    ("rain", "rain", "rain [ reɪn ] — дождь"),
    ("rule", "rule", "rule [ ruːl ] — правило"),
    ("govern", "govern", "govern [ ˈɡʌv. ə n ] — управлять"),
    ("pull", "pull", "pull [pʊl] — тянуть"),
    ("cold", "cold", "cold [ kəʊld ] — холодный"),
    ("notice", "notice", "notice [ ˈnəʊ.tɪs ] — уведомление / замечать"),
    ("voice", "voice", "voice [ vɔɪs ] — голос"),
    ("energy", "energy", "energy [ ˈen.ə.dʒi ] — энергия"),
    ("hunt", "hunt", "hunt [ hʌnt ] — охотититься"),
    ("probable", "probable", "probable [ ˈprɒb.ə.b ə l ] — вероятный"),
    ("bed", "bed", "bed [ bed ] — кровать"),
    ("brother", "brother", "brother [ ˈbrʌð.ə r ] — брат"),
    ("egg", "egg", "egg [ e ɡ ] — яйцо"),
    ("ride", "ride", "ride [ raɪd ] — ездить / поездка"),
    ("cell", "cell", "cell [ sel ] — клетка / мобильный ( амер. )"),
    ("believe", "believe", "believe [ bɪˈliːv ] — верить"),
    ("perhaps", "perhaps", "perhaps [ pəˈhæps ] — возможно"),
    ("pick", "pick", "pick [ pɪk ] — выбирать"),
    ("sudden", "sudden", "sudden [ ˈsʌd. ə n ] — внезапный"),
    ("count", "count", "count [ kaʊnt ] — считать"),
    ("square", "square", "square [ skwe ə r ] — квадрат / площадь"),
    ("reason", "reason", "reason [ ˈriː.z ə n ] — причина"),
    ("length", "length", "length [ leŋθ ] — длина"),
    ("represent", "represent", "represent [ ˌ rep. rɪˈzent ] — представлять"),
    ("art", "art", "art [ ɑːt ] — искусство"),
    ("subject", "subject", "subject [ ˈsʌb. dʒekt ] — предмет"),
    ("region", "region", "region [ ˈriː.dʒ ə n ] — регион"),
    ("size", "size", "size [ saɪz ] — размер"),
    ("vary", "vary", "vary [ ˈveə.ri ] — меняться / варьировать"),
    ("settle", "settle", "settle [ ˈ set. ə l ] — селиться"),
    ("speak", "speak", "speak [ spiːk ] — говорить"),
    ("weight", "weight", "weight [ weɪt ] — вес"),
    ("general", "general", "general [ ˈdʒen. ə r. ə l ] — главный / общий"),
    ("ice", "ice", "ice [ aɪs ] — лед"),
    ("matter", "matter", "matter [ ˈmæt.ə r ] — иметь значение / предмет / материя"),
    ("circle", "circle", "circle [ ˈsɜː.k ə l ] — круг"),
    ("pair", "pair", "pair [ pe ə r ] — пара"),
    ("include", "include", "include [ ɪnˈkluːd ] — включать в себя"),
    ("divide", "divide", "divide [ dɪˈvaɪd ] — разделять"),
    ("syllable", "syllable", "syllable [ ˈsɪl.ə.b ə l ] — слог"),
    ("felt", "felt", "felt [ felt ] — чувствовал"),
    ("grand", "grand", "grand [ ɡrænd ] — большой / великий"),
    ("ball", "ball", "ball [ bɔːl ] — мяч"),
    ("yet", "yet", "yet [ jet ] — еще"),
    ("wave", "wave", "wave [ weɪv ] — волна"),
    ("drop", "drop", "drop [ drɒp ] — капля / бросать"),
    ("heart", "heart", "heart [ hɑːt ] — сердце"),
    ("AM", "AM", "AM [ ˌ e ɪ ˈ em ] — до полудня"),
    ("present", "present", "present [ ˈ prez. ə nt ] — подарок / настоящий"),
    ("heavy", "heavy", "heavy [ ˈ hev. i ] — тяжелый"),
    ("dance", "dance", "dance [ dɑːns ] — танец / танцевать"),
    ("engine", "engine", "engine [ ˈ en. dʒɪn ] — двигатель"),
    ("position", "position", "position [ pəˈzɪʃ. ə n ] — позиция"),
    ("arm", "arm", "arm [ ɑːm ] — рука"),
    ("wide", "wide", "wide [ waɪd ] — широкий / повсюду"),
    ("sail", "sail", "sail [ seɪl ] — паруса / плавать"),
    ("material", "material", "material [ məˈtɪə.ri.əl ] — материал"),
    ("fraction", "fraction", "fraction [ ˈfræk.ʃ ə n ] — доля"),
    ("forest", "forest", "forest [ ˈfɒr.ɪst ] — лес"),
    ("sit", "sit", "sit [ sɪt ] — сидеть"),
    ("race", "race", "race [ reɪs ] — гонка / раса"),
    ("window", "window", "window [ ˈwɪn. dəʊ ] — окно"),
    ("store", "store", "store ( амер. ) [ stɔː r ] — магазин"),
    ("summer", "summer", "summer [ ˈsʌm.ə r ] — лето"),
    ("train", "train", "train [ treɪn ] — поезд"),
    ("sleep", "sleep", "sleep [ sliːp ] — спать"),
    ("prove", "prove", "prove [ pruːv ] — доказывать"),
    ("alone", "alone", "alone [ əˈləʊn ] — один / одинокий"),
    ("leg", "leg", "leg [ le ɡ ] — нога"),
    ("exercise", "exercise", "exercise [ ˈ ek. s ə. saɪz ] — упражнение"),
    ("wall", "wall", "wall [ wɔːl ] — стена"),
    ("catch", "catch", "catch [ kætʃ ] — поймать"),
    ("mount", "mount", "mount [ maʊnt ] — взбираться / монтировать"),
    ("wish", "wish", "wish [ wɪʃ ] — желать"),
    ("sky", "sky", "sky [ ska ɪ ] — небо"),
    ("board", "board", "board [ bɔːd ] — доска"),
    ("joy", "joy", "joy [ dʒɔɪ ] — радость"),
    ("winter", "winter", "winter [ ˈwɪn. t ə r ] — зима"),
    ("somebody", "somebody", "somebody [ ˈsʌm. b ə. di ] — кто-то"),
    ("written", "written", "written [ ˈrɪt. ə n ] — написанный"),
    ("wild", "wild", "wild [ waɪld ] — дикий"),
    ("instrument", "instrument", "instrument [ ˈɪn. str ə. mənt ] — инструмент"),
    ("kept", "kept", "kept [ kept ] — сохранил"),
    ("glass", "glass", "glass [ ɡlɑːs ] — стекло"),
    ("grass", "grass", "grass [ ɡrɑːs ] — трава"),
    ("cow", "cow", "cow [ ka ʊ ] — корова"),
    ("job", "job", "job [ dʒɒb ] — работа"),
    ("edge", "edge", "edge [ ed ʒ ] — край"),
    ("sign", "sign", "sign [ saɪn ] — подписывать / знак"),
    ("visit", "visit", "visit [ ˈvɪz.ɪt ] — посещать"),
    ("past", "past", "past [ pɑːst ] — прошлое"),
    ("soft", "soft", "soft [ sɒft ] — мягкий"),
    ("fun", "fun", "fun [ fʌn ] — веселый / веселье"),
    ("bright", "bright", "bright [ braɪt ] — яркий"),
    ("gas", "gas", "gas [ ɡæs ] — газ / бензин ( амер. )"),
    ("weather", "weather", "weather [ ˈweð.ə r ] — погода"),
    ("month", "month", "month [ mʌnθ ] — месяц"),
    ("million", "million", "million [ ˈmɪl. jən ] — миллион"),
    ("bear", "bear", "bear [ be ə r ] — медведь / выносить (терпеть)"),
    ("finish", "finish", "finish [ ˈfɪn.ɪʃ ] — закончить"),
    ("happy", "happy", "happy [ ˈhæp. i ] — счастливый"),
    ("hope", "hope", "hope [ həʊp ] — надежда / надеяться"),
    ("flower", "flower", "flower [ flaʊə r ] — цветок"),
    ("clothes", "clothes", "clothes [ kləʊðz ] — одежда"),
    ("strange", "strange", "strange [ streɪndʒ ] — странный"),
    ("gone", "gone", "gone [ ɡɒn ] — ушедший"),
    ("trade", "trade", "trade [ treɪd ] — торговля"),
    ("melody", "melody", "melody [ ˈmel.ə.di ] — мелодия"),
    ("trip", "trip", "trip [ trɪp ] — поездка"),
    ("office", "office", "office [ ˈɒf.ɪs ] — офис"),
    ("receive", "receive", "receive [ rɪˈsiːv ] — получать"),
    ("row", "row", "row [ rəʊ ] — ряд"),
    ("mouth", "mouth", "mouth [ maʊθ ] — рот"),
    ("exact", "exact", "exact [ ɪɡˈzækt ] — точный"),
    ("symbol", "symbol", "symbol [ ˈsɪm. b ə l ] — символ"),
    ("die", "die", "die [ da ɪ ] — умирать"),
    ("least", "least", "least [ liːst ] — наименее / меньше всего"),
    ("trouble", "trouble", "trouble [ ˈtrʌb. ə l ] — проблема"),
    ("shout", "shout", "shout [ ʃaʊt ] — кричать"),
    ("except", "except", "except [ ɪkˈsept ] — кроме / исключая"),
    ("writer", "writer", "writer [ ˈraɪ.tə r ] — писатель"),
    ("seed", "seed", "seed [siːd] — семя"),
    ("tone", "tone", "tone [ təʊn ] — тон"),
    ("join", "join", "join [ dʒɔɪn ] — присоединяться"),
    ("suggest", "suggest", "suggest [ səˈdʒest ] — предлагать"),
    ("clean", "clean", "clean [ kliːn ] — чисто / чистый"),
    ("break", "break", "break [ breɪk ] — перерыв / ломать"),
    ("lady", "lady", "lady [ ˈleɪ.di ] — леди"),
    ("yard", "yard", "yard [ jɑːd ] — двор"),
    ("rise", "rise", "rise [ raɪz ] — рост / подниматься"),
    ("bad", "bad", "bad [ bæd ] — плохой"),
    ("blow", "blow", "blow [ bləʊ ] — удар / дуть"),
    ("oil", "oil", "oil [ ɔɪl ] — масло"),
    ("blood", "blood", "blood [ blʌd ] — кровь"),
    ("touch", "touch", "touch [ tʌtʃ ] — трогать / прикосновение"),
    ("goal", "goal", "goal [ ɡəʊl ] — цель"),
    ("cent", "cent", "cent [ sent ] — цент"),
    ("mix", "mix", "mix [ mɪks ] — смесь / смешивать"),
    ("team", "team", "team [ tiːm ] — команда"),
    ("wire", "wire", "wire [ waɪə r ] — проволока"),
    ("cost", "cost", "cost [ kɒst ] — стоимость"),
    ("lost", "lost", "lost [ lɒst ] — потерял / потерянный"),
    ("brown", "brown", "brown [ braʊn ] — коричневый"),
    ("wear", "wear", "wear [ we ə r ] — носить"),
    ("garden", "garden", "garden [ ˈɡɑː.d ə n ] — сад"),
    ("equal", "equal", "equal [ ˈiː.kwəl ] — равный"),
    ("sent", "sent", "sent [ sent ] — отправил / отправленный"),
    ("choose", "choose", "choose [ tʃuːz ] — выбирать"),
    ("feel", "feel", "feel [ fiːl ] — чувствовать"),
    ("fit", "fit", "fit [ fɪt ] — соответствовать / подходить"),
    ("flow", "flow", "flow [ fləʊ ] — поток / течь"),
    ("fair", "fair", "fair [ fe ə r ] — ярмарка / честный"),
    ("bank", "bank", "bank [ bæŋk ] — банк"),
    ("collect", "collect", "collect [ kəˈlekt ] — собирать"),
    ("save", "save", "save [ seɪv ] — сохранять"),
    ("control", "control", "control [ kənˈtrəʊl ] — контроль / контролировать"),
    ("decimal", "decimal", "decimal [ ˈdes.ɪ.məl ] — десятичный"),
    ("ear", "ear", "ear [ ɪə r ] — ухо"),
    ("else", "else", "else [ els ] — еще"),
    ("quite", "quite", "quite [ kwaɪt ] — довольно"),
    ("broke", "broke", "broke [ brəʊk ] — сломал / без денег"),
    ("case", "case", "case [ keɪs ] — случай"),
    ("middle", "middle", "middle [ ˈmɪd. ə l ] — средний"),
    ("kill", "kill", "kill [ kɪl ] — убивать"),
    ("son", "son", "son [ sʌn ] — сын"),
    ("lake", "lake", "lake [ leɪk ] — озеро"),
    ("moment", "moment", "moment [ ˈməʊ.mənt ] — момент"),
    ("scale", "scale", "scale [ skeɪl ] — шкала"),
    ("loud", "loud", "loud [ laʊd ] — громко"),
    ("spring", "spring", "spring [ sprɪŋ ] — весна"),
    ("observe", "observe", "observe [ əbˈzɜːv ] — наблюдать"),
    ("child", "child", "child [ tʃaɪld ] — ребенок"),
    ("straight", "straight", "straight [ streɪt ] — прямо / прямой"),
    ("consonant", "consonant", "consonant [ ˈkɒn. s ə. nənt ] — согласный (звук)"),
    ("nation", "nation", "nation [ ˈneɪ.ʃ ə n ] — нация"),
    ("dictionary", "dictionary", "dictionary [ ˈdɪk.ʃ ə n. ə r. i ] — словарь"),
    ("milk", "milk", "milk [ mɪlk ] — молоко"),
    ("speed", "speed", "speed [ spiːd ] — скорость"),
    ("method", "method", "method [ ˈmeθ.əd ] — метод"),
    ("organ", "organ", "organ [ ˈɔː.ɡən ] — орган"),
    ("pay", "pay", "pay [ pe ɪ ] — платить"),
    ("age", "age", "age [ eɪdʒ ] — возраст"),
    ("section", "section", "section [ ˈsek.ʃ ə n ] — раздел"),
    ("dress", "dress", "dress [ dres ] — платье / одеваться"),
    ("cloud", "cloud", "cloud [ klaʊd ] — облако"),
    ("surprise", "surprise", "surprise [ səˈpraɪz ] — сюрприз"),
    ("quiet", "quiet", "quiet [ ˈkwaɪ.ət ] — тихо / тихий"),
    ("stone", "stone", "stone [ stəʊn ] — камень"),
    ("tiny", "tiny", "tiny [ ˈtaɪ.ni ] — крошечный"),
    ("climb", "climb", "climb [ klaɪm ] — подъем / взбираться"),
    ("cool", "cool", "cool [ kuːl ] — крутой / прохладно"),
    ("design", "design", "design [ dɪˈzaɪn ] — дизайн"),
    ("poor", "poor", "poor [ pɔː r ] — бедный"),
    ("lot", "lot", "lot [ lɒt ] — много"),
    ("explain", "explain", "explain [ ɪkˈspleɪn ] — объяснять"),
    ("bottom", "bottom", "bottom [ ˈbɒt. ə m ] — низ"),
    ("key", "key", "key [ ki ː ] — ключ"),
    ("iron", "iron", "iron [ aɪən ] — железо"),
    ("single", "single", "single [ ˈsɪŋ.ɡ ə l ] — один"),
    ("stick", "stick", "stick [ stɪk ] — придерживаться / приклеивать"),
    ("flat", "flat", "flat [ flæt ] — квартира ( брит. ) / плоский"),
    ("twenty", "twenty", "twenty [ ˈ twen. ti ] — двадцать"),
    ("skin", "skin", "skin [ skɪn ] — кожа"),
    ("smile", "smile", "smile [ smaɪl ] — улыбка"),
    ("crease", "crease", "crease [ kriːs ] — складка / мять"),
    ("hole", "hole", "hole [ həʊl ] — дыра"),
    ("jump", "jump", "jump [ dʒʌmp ] — прыгать"),
    ("baby", "baby", "baby [ ˈbeɪ.bi ] — ребенок"),
    ("eight", "eight", "eight [ eɪt ] — восемь"),
    ("village", "village", "village [ ˈvɪl.ɪdʒ ] — деревня"),
    ("meet", "meet", "meet [ miːt ] — встречать"),
    ("root", "root", "root [ ruːt ] — корень"),
    ("buy", "buy", "buy [ ba ɪ ] — покупать"),
    ("raise", "raise", "raise [ reɪz ] — поднимать / повышать"),
    ("solve", "solve", "solve [ sɒlv ] — решать"),
    ("metal", "metal", "metal [ ˈ met. ə l ] — металл"),
    ("whether", "whether", "whether [ ˈweð.ə r ] — будь то / ли"),
    ("push", "push", "push [ pʊʃ ] — давить / нажимать"),
    ("seven", "seven", "seven [ ˈ sev. ə n ] — семь"),
    ("paragraph", "paragraph", "paragraph [ ˈpær.ə.ɡrɑːf ] — параграф"),
    ("third", "third", "third [ θɜːd ] — третий"),
    ("shall", "shall", "shall [ ʃæl ] — должен"),
    ("held", "held", "held [ held ] — держал"),
    ("hair", "hair", "hair [ he ə r ] — волосы"),
    ("describe", "describe", "describe [ dɪˈskraɪb ] — описывать"),
    ("cook", "cook", "cook [ kʊk ] — готовить"),
    ("floor", "floor", "floor [ flɔː r ] — пол"),
    ("either", "either", "either [ ˈaɪ.ðə r ] — или"),
    ("result", "result", "result [ rɪˈzʌlt ] — результат"),
    ("burn", "burn", "burn [ bɜːn ] — гореть / ожог"),
    ("hill", "hill", "hill [ hɪl ] — холм"),
    ("safe", "safe", "safe [ seɪf ] — безопасный"),
    ("cat", "cat", "cat [ kæt ] — кот / кошка"),
    ("century", "century", "century [ ˈ sen. t ʃ ə r. i ] — век / столетие"),
    ("consider", "consider", "consider [ kənˈsɪd.ə r ] — рассматривать"),
    ("type", "type", "type [ taɪp ] — тип / печатать"),
    ("law", "law", "law [ lɔː ] — закон"),
    ("bit", "bit", "bit [ bɪt ] — немного / часть"),
    ("coast", "coast", "coast [ kəʊst ] — берег"),
    ("copy", "copy", "copy [ ˈkɒp. i ] — копировать / копия"),
    ("phrase", "phrase", "phrase [ freɪz ] — фраза / формулировать"),
    ("silent", "silent", "silent [ ˈsaɪlənt ] — тихий"),
    ("tall", "tall", "tall [ tɔːl ] — высокий"),
    ("sand", "sand", "sand [ sænd ] — песок"),
    ("soil", "soil", "soil [ sɔɪl ] — почва"),
    ("roll", "roll", "roll [ rəʊl ] — вертеть"),
    ("temperature", "temperature", "temperature [ ˈ tem. pr ə. tʃə r ] — температура"),
    ("finger", "finger", "finger [ ˈfɪŋ.ɡə r ] — палец"),
    ("industry", "industry", "industry [ ˈɪn. d ə. stri ] — индустрия"),
    ("value", "value", "value [ ˈvæl. ju ː ] — значение / стоимость / ценность"),
    ("fight", "fight", "fight [ faɪt ] — драка / бороться"),
    ("lie", "lie", "lie [ la ɪ ] — ложь / лгать"),
    ("beat", "beat", "beat [ biːt ] — бить / ритм"),
    ("excite", "excite", "excite [ ɪkˈsaɪt ] — возбуждать"),
    ("natural", "natural", "natural [ˈnætʃ.ər.əl / ] — натуральный"),
    ("view", "view", "view [ vju ː ] — вид"),
    ("sense", "sense", "sense [ sens ] — смысл / чувство"),
    ("capital", "capital", "capital [ ˈkæp.ɪ.t ə l ] — столица"),
    ("won’t", "won’t", "won’t [ wəʊnt ] — не будет"),
    ("chair", "chair", "chair [ tʃeə r ] — стул"),
    ("danger", "danger", "danger [ ˈdeɪn. dʒə r ] — опасность"),
    ("fruit", "fruit", "fruit [ fruːt ] — фрукт"),
    ("rich", "rich", "rich [ rɪtʃ ] — богатый"),
    ("thick", "thick", "thick [ θɪk ] — толстый"),
    ("soldier", "soldier", "soldier [ ˈsəʊl. dʒə r ] — солдат"),
    ("process", "process", "process [ ˈprəʊ.ses ] — процесс / подвергать обработке"),
    ("operate", "operate", "operate [ ˈɒp. ə r. eɪt ] — управлять"),
    ("practice", "practice", "practice [ ˈpræk. tɪs ] — практиковать / практика"),
    ("separate", "separate", "separate [ ˈ sep ə reɪt ] — разделять"),
    ("difficult", "difficult", "difficult [ ˈdɪf.ɪ.k ə lt ] — сложный"),
    ("doctor", "doctor", "doctor [ ˈdɒk. t ə r ] — доктор"),
    ("please", "please", "please [ pliːz ] — пожалуйста / угождать"),
    ("protect", "protect", "protect [ prəˈtekt ] — защищать"),
    ("noon", "noon", "noon [ nuːn ] — полдень"),
    ("crop", "crop", "crop [ krɒp ] — обрезать / урожай"),
    ("modern", "modern", "modern [ ˈmɒd. ə n ] — современный"),
    ("element", "element", "element [ ˈel.ɪ.mənt ] — элемент"),
    ("hit", "hit", "hit [ hɪt ] — удар / бить"),
    ("student", "student", "student [ ˈstjuː.d ə nt ] — студент"),
    ("corner", "corner", "corner [ ˈkɔː.nə r ] — угол"),
    ("party", "party", "party [ ˈpɑː.ti ] — вечеринка / партия"),
    ("supply", "supply", "supply [ səˈplaɪ ] — поставка / снабжать"),
    ("whose", "whose", "whose [ huːz ] — чьи"),
    ("locate", "locate", "locate [ ləʊˈkeɪt ] — размещать"),
    ("ring", "ring", "ring [ rɪŋ ] — кольцо"),
    ("character", "character", "character [ ˈkær.ə k. t ə r ] — персонаж / характер"),
    ("insect", "insect", "insect [ ˈɪn. sekt ] — насекомое"),
    ("caught", "caught", "caught [ kɔːt ] — поймал / пойманный"),
    ("period", "period", "period [ ˈpɪə.ri.əd ] — период / точка"),
    ("indicate", "indicate", "indicate [ ˈɪn. d ɪ. keɪt ] — указывать"),
    ("radio", "radio", "radio [ ˈreɪ.di.əʊ ] — радио"),
    ("spoke", "spoke", "spoke [ spəʊk ] — говорил"),
    ("atom", "atom", "atom [ ˈæt.əm ] — атом"),
    ("human", "human", "human [ ˈhjuː.mən ] — человек"),
    ("history", "history", "history [ ˈhɪs. t ə r. i ] — история"),
    ("effect", "effect", "effect [ ɪˈfekt ] — эффект / следствие"),
    ("electric", "electric", "electric [ iˈlek. trɪk ] — электрический"),
    ("expect", "expect", "expect [ ɪkˈspekt ] — ожидать"),
    ("bone", "bone", "bone [ bəʊn ] — кость"),
    ("rail", "rail", "rail [ reɪl ] — рельс / железнодорожный путь"),
    ("imagine", "imagine", "imagine [ ɪˈmædʒ.ɪn ] — представлять"),
    ("provide", "provide", "provide [ prəˈvaɪd ] — предоставлять"),
    ("agree", "agree", "agree [ əˈɡriː ] — соглашаться"),
    ("thus", "thus", "thus [ ðʌs ] — таким образом"),
    ("gentle", "gentle", "gentle [ ˈdʒen. t ə l ] — нежный"),
    ("woman", "woman", "woman [ ˈwʊm.ən ] — женщина"),
    ("captain", "captain", "captain [ ˈkæp. tɪn ] — капитан"),
    ("guess", "guess", "guess [ ɡ es ] — предположение / угадывать"),
    ("necessary", "necessary", "necessary [ ˈ nes. ə. ser. i ] — необходимый"),
    ("sharp", "sharp", "sharp [ ʃɑːp ] — острый / умный / стильный (о человеке)"),
    ("wing", "wing", "wing [ wɪŋ ] — крыло"),
    ("create", "create", "create [ kriˈeɪt ] — создавать"),
    ("neighbour", "neighbour", "neighbour [ ˈneɪ.bə r ] — сосед"),
    ("wash", "wash", "wash [ wɒʃ ] — мыть"),
    ("bat", "bat", "bat [ bæt ] — летучая мышь / бита"),
    ("rather", "rather", "rather [ ˈrɑː.ðə r ] — скорее"),
    ("crowd", "crowd", "crowd [ kraʊd ] — толпа"),
    ("corn", "corn", "corn [ kɔːn ] — кукуруза"),
    ("compare", "compare", "compare [ kəmˈpeə r ] — сравнивать"),
    ("poem", "poem", "poem [ ˈpəʊ.ɪm ] — стих"),
    ("string", "string", "string [ strɪŋ ] — струна"),
    ("bell", "bell", "bell [ bel ] — колокол"),
    ("depend", "depend", "depend [ dɪˈpend ] — зависеть"),
    ("meat", "meat", "meat [ miːt ] — мясо"),
    ("rub", "rub", "rub [ rʌb ] — тереть"),
    ("tube", "tube", "tube [ tʃuːb ] — трубка / метро (в Лондоне)"),
    ("famous", "famous", "famous [ ˈfeɪ.məs ] — известный"),
    ("dollar", "dollar", "dollar [ ˈdɒl.ə r ] — доллар"),
    ("stream", "stream", "stream [ striːm ] — поток / течь"),
    ("fear", "fear", "fear [ fɪə r ] — страх / бояться"),
    ("sight", "sight", "sight [ saɪt ] — взгляд / вид / зрение"),
    ("thin", "thin", "thin [ θɪn ] — тонкий"),
    ("triangle", "triangle", "triangle [ ˈtraɪ.æŋ.ɡ ə l ] — треугольник"),
    ("planet", "planet", "planet [ ˈplæn.ɪt ] — планета"),
    ("hurry", "hurry", "hurry [ ˈhʌr. i ] — торопиться / спешка"),
    ("chief", "chief", "chief [ tʃiːf ] — шеф"),
    ("colony", "colony", "colony [ ˈkɒl.ə.ni ] — колония"),
    ("clock", "clock", "clock [ klɒk ] — часы"),
    ("mine", "mine", "mine [ maɪn ] — мой"),
    ("tie", "tie", "tie [ ta ɪ ] — галстук / завязывать"),
    ("enter", "enter", "enter [ ˈ en. t ə r ] — вход / входить"),
    ("major", "major", "major [ ˈmeɪ.dʒə r ] — майор / основной"),
    ("fresh", "fresh", "fresh [ fre ʃ ] — свежий"),
    ("search", "search", "search [ sɜːtʃ ] — поиск / искать"),
    ("send", "send", "send [ send ] — посылать"),
    ("yellow", "yellow", "yellow [ ˈjel.əʊ ] — желтый"),
    ("gun", "gun", "gun [ ɡʌn ] — пистолет / ружье"),
    ("allow", "allow", "allow [ əˈlaʊ ] — позволять"),
    ("print", "print", "print [ prɪnt ] — печать / печатать"),
    ("dead", "dead", "dead [ ded ] — мертвый"),
    ("spot", "spot", "spot [ spɒt ] — место / пятно"),
    ("desert", "desert", "desert [ ˈdez.ət ] — пустыня"),
    ("suit", "suit", "suit [ suːt ] — костюм / подходить"),
    ("current", "current", "current [ ˈkʌr. ə nt ] — текущий"),
    ("lift", "lift", "lift [ lɪft ] — поднимать / лифт ( брит. )"),
    ("rose", "rose", "rose [ rəʊz ] — роза"),
    ("arrive", "arrive", "arrive [ əˈraɪv ] — прибывать"),
    ("master", "master", "master [ ˈmɑː.stə r ] — мастер / главный / справляться"),
    ("track", "track", "track [ træk ] — трек / след"),
    ("parent", "parent", "parent [ ˈpeə.r ə nt ] — родитель"),
    ("shore", "shore", "shore [ ʃɔː r ] — побережье"),
    ("division", "division", "division [ dɪˈvɪʒ. ə n ] — деление"),
    ("sheet", "sheet", "sheet [ ʃiːt ] — лист / простынь"),
    ("substance", "substance", "substance [ ˈsʌb. st ə ns ] — вещество"),
    ("favour", "favour", "favour [ ˈfeɪ.və r ] — одолжение"),
    ("connect", "connect", "connect [ kəˈnekt ] — соединять"),
    ("post", "post", "post [ pəʊst ] — почта / после"),
    ("spend", "spend", "spend [ spend ] — тратить"),
    ("chord", "chord", "chord [ kɔːd ] — аккорд"),
    ("fat", "fat", "fat [ fæt ] — жир / жирный"),
    ("glad", "glad", "glad [ ɡlæd ] — рад"),
    ("original", "original", "original [ əˈrɪdʒ. ə n. ə l ] — оригинальный"),
    ("share", "share", "share [ ʃ e ə r ] — делиться"),
    ("station", "station", "station [ ˈsteɪ.ʃ ə n ] — станция"),
    ("dad", "dad", "dad [ dæd ] — папа"),
    ("bread", "bread", "bread [ bred ] — хлеб"),
    ("charge", "charge", "charge [ tʃɑːdʒ ] — заряд / заряжать"),
    ("proper", "proper", "proper [ ˈprɒp.ə r ] — правильный"),
    ("bar", "bar", "bar [ bɑː r ] — бар"),
    ("offer", "offer", "offer [ ˈɒf.ə r ] — предлагать / предложение"),
    ("segment", "segment", "segment [ ˈseɡ.mənt ] — часть / сегмент"),
    ("slave", "slave", "slave [ sleɪv ] — раб"),
    ("duck", "duck", "duck [ dʌk ] — утка"),
    ("instant", "instant", "instant [ ˈɪn. stənt ] — мгновенный"),
    ("market", "market", "market [ ˈmɑː.kɪt ] — рынок"),
    ("degree", "degree", "degree [ dɪˈɡriː ] — температура"),
    ("populate", "populate", "populate [ ˈpɒp. j ə. leɪt ] — населять"),
    ("education", "education", "education [ ˌedʒ.uˈkeɪ.ʃ ə n ] — образование"),
    ("dear", "dear", "dear [ dɪə r ] — дорогая"),
    ("enemy", "enemy", "enemy [ ˈen.ə.mi ] — враг"),
    ("reply", "reply", "reply [ rɪˈplaɪ ] — ответ / отвечать"),
    ("drink", "drink", "drink [ drɪŋk ] — напиток / пить"),
    ("occur", "occur", "occur [ əˈkɜː r ] — происходить"),
    ("support", "support", "support [ səˈpɔːt ] — поддержка / поддерживать"),
    ("speech", "speech", "speech [ spiːtʃ ] — речь"),
    ("nature", "nature", "nature [ ˈneɪ.tʃə r ] — природа"),
    ("range", "range", "range [ reɪndʒ ] — диапазон"),
    ("steam", "steam", "steam [ stiːm ] — пар"),
    ("motion", "motion", "motion [ ˈməʊ.ʃ ə n ] — движение"),
    ("path", "path", "path [ pɑːθ ] — путь"),
    ("liquid", "liquid", "liquid [ ˈlɪk. wɪd ] — жидкость"),
    ("violence", "violence", "violence [ ˈvaɪə.l ə ns ] — жестокость"),
    ("meant", "meant", "meant [ ment ] — значил"),
    ("quotient", "quotient", "quotient [ ˈkwəʊ.ʃ ə nt ] — частное"),
    ("teeth", "teeth", "teeth [ tiːθ ] — зубы"),
    ("shell", "shell", "shell [ ʃ el ] — ракушка"),
    ("neck", "neck", "neck [ nek ] — шея"),
    ("oxygen", "oxygen", "oxygen [ ˈɒk. s ɪ. dʒən ] — кислород"),
    ("sugar", "sugar", "sugar [ ˈʃʊɡ.ə r ] — сахар"),
    ("death", "death", "death [ de θ ] — смерть"),
    ("pretty", "pretty", "pretty [ ˈprɪt. i ] — красивый / довольно"),
    ("skill", "skill", "skill [ skɪl ] — умение"),
    ("women", "women", "women [ ˈwɪm.ɪn ] — женщины"),
    ("season", "season", "season [ ˈsiː.z ə n ] — сезон / время года"),
    ("solution", "solution", "solution [ səˈluː.ʃ ə n ] — решение"),
    ("magnet", "magnet", "magnet [ ˈmæɡ.nət ] — магнит"),
    ("silver", "silver", "silver [ ˈsɪl. v ə r ] — серебро"),
    ("thanks", "thanks", "thanks [ θæŋks ] — спасибо"),
    ("lunch", "lunch", "lunch [ lʌntʃ ] — ужин"),
    ("match", "match", "match [ mætʃ ] — совпадать / матч"),
    ("treat", "treat", "treat [ triːt ] — угощение / обращаться"),
    ("especially", "especially", "especially [ ɪˈspeʃ. ə l. i ] — особенно"),
    ("fail", "fail", "fail [ feɪl ] — провал / терпеть провал"),
    ("afraid", "afraid", "afraid [ əˈfreɪd ] — испуганный"),
    ("huge", "huge", "huge [ hjuːdʒ ] — огромный"),
    ("sister", "sister", "sister [ ˈsɪs. t ə r ] — сестра"),
    ("steel", "steel", "steel [ stiːl ] — сталь"),
    ("discuss", "discuss", "discuss [ dɪˈskʌs ] — обсуждать"),
    ("forward", "forward", "forward [ ˈfɔː.wəd ] — вперед"),
    ("similar", "similar", "similar [ ˈsɪm.ɪ.lə r ] — похожий"),
    ("guide", "guide", "guide [ ɡaɪd ] — руководство / направлять"),
    ("experience", "experience", "experience [ ɪkˈspɪə.ri.əns ] — опыт"),
    ("score", "score", "score [ skɔː r ] — очки / счет"),
    ("apple", "apple", "apple [ ˈæp. ə l ] — яблоко"),
    ("evidence", "evidence", "evidence [ ˈev.ɪ.d ə ns ] — доказательства"),
    ("message", "message", "message [ ˈmes.ɪdʒ ] — сообщение"),
    ("movie", "movie", "movie [ ˈmuː.vi ] — фильм ( амер. )"),
    ("coat", "coat", "coat [ kəʊt ] — пальто"),
    ("mass", "mass", "mass [ mæs ] — масса"),
    ("card", "card", "card [ kɑːd ] — карта"),
    ("band", "band", "band [ bænd ] — группа"),
    ("rope", "rope", "rope [ rəʊp ] — веревка"),
    ("slip", "slip", "slip [ slɪp ] — скользить"),
    ("win", "win", "win [ wɪn ] — побеждать"),
    ("dream", "dream", "dream [ driːm ] — мечта / мечтать / сон"),
    ("evening", "evening", "evening [ ˈiːv. nɪŋ ] — вечер"),
    ("condition", "condition", "condition [ kənˈdɪʃ. ə n ] — состояние"),
    ("feed", "feed", "feed [ fiːd ] — кормить"),
    ("tool", "tool", "tool [ tuːl ] — инструмент"),
    ("total", "total", "total [ ˈtəʊ.t ə l ] — сумма"),
    ("basic", "basic", "basic [ ˈbeɪ.sɪk ] — базовый"),
    ("smell", "smell", "smell [ smel ] — запах"),
    ("valley", "valley", "valley [ ˈvæl. i ] — долина"),
    ("not", "not", "not [ nɒt ] — не"),
    ("double", "double", "double [ˈdʌb.əl] — двойной / вдвойне / двойник"),
    ("seat", "seat", "seat [ siːt ] — место"),
    ("continue", "continue", "continue [ kənˈtɪn. ju ː ] — продолжать"),
    ("news", "news", "news [ njuːz ] — новости"),
    ("police", "police", "police [ pəˈliːs ] — полиция"),
    ("hat", "hat", "hat [ hæt ] — шляпа"),
    ("sell", "sell", "sell [ sel ] — продавать"),
    ("success", "success", "success [ səkˈses ] — успех"),
    ("company", "company", "company [ ˈkʌm. p ə. ni ] — компания"),
    ("security", "security", "security [ sɪˈkjʊə.rə.ti ] — безопасность / охрана"),
    ("event", "event", "event [ ɪˈvent ] — событие"),
    ("particular", "particular", "particular [ pəˈtɪk. j ə. l ə r ] — особенный / конкретный"),
    ("deal", "deal", "deal [ diːl ] — сделка / часть / разбираться"),
    ("swim", "swim", "swim [ swɪm ] — плавать"),
    ("term", "term", "term [ tɜːm ] — срок / семестр / термин"),
    ("opposite", "opposite", "opposite [ ˈɒp.ə.zɪt ] — напротив / противоположный"),
    ("wife", "wife", "wife [ waɪf ] — жена"),
    ("shoes", "shoes", "shoes [ ʃuːz ] — обувь / туфли"),
    ("shoulders", "shoulders", "shoulders [ ˈʃəʊl. d ə r z ] — плечи"),
    ("spread", "spread", "spread [ spred ] — распространение / распространять"),
    ("arrange", "arrange", "arrange [ əˈreɪndʒ ] — организовывать"),
    ("camp", "camp", "camp [ kæmp ] — лагерь"),
    ("invent", "invent", "invent [ ɪnˈvent ] — изобретать"),
    ("cotton", "cotton", "cotton [ ˈkɒt. ə n ] — хлопок"),
    ("born", "born", "born [ bɔːn ] — родиться"),
    ("determine", "determine", "determine [ dɪˈtɜː.mɪn ] — определять"),
    ("quarter", "quarter", "quarter [ ˈkwɔː.tə r ] — четверть"),
    ("nine", "nine", "nine [ naɪn ] — девять"),
    ("remove", "remove", "remove [ rɪˈmuːv ] — удалять"),
    ("noise", "noise", "noise [ nɔɪz ] — шум"),
    ("level", "level", "level [ ˈ lev. ə l ] — уровень"),
    ("chance", "chance", "chance [ tʃɑːns ] — шанс"),
    ("gather", "gather", "gather [ ˈɡæð.ə r]— собирать"),
    ("shop", "shop", "shop [ ʃɒp ] — магазин ( брит. )"),
    ("stretch", "stretch", "stretch [ stret ʃ ] — растягивать"),
    ("throw", "throw", "throw [ θrəʊ ] — бросать"),
    ("shine", "shine", "shine [ ʃaɪn ] — сиять"),
    ("property", "property", "property [ ˈprɒp.ə.ti ] — собственность"),
    ("issue", "issue", "issue [ ˈɪʃ.uː ] — проблема"),
    ("legal", "legal", "legal [ ˈliː.ɡ ə l ] — законный"),
    ("select", "select", "select [ sɪˈlekt ] — выбирать"),
    ("wrong", "wrong", "wrong [ rɒŋ ] — неправильный"),
    ("gray", "gray", "gray [ ɡ re ɪ ] — серый"),
    ("repeat", "repeat", "repeat [ rɪˈpiːt ] — повторять"),
    ("require", "require", "require [ rɪˈkwaɪə r ] — требоваться"),
    ("broad", "broad", "broad [ brɔːd ] — широкий"),
    ("prepare", "prepare", "prepare [ prɪˈpeə r ] — подготавливать"),
    ("salt", "salt", "salt [ sɒlt ] — соль / соленый"),
    ("nose", "nose", "nose [ nəʊz ] — нос"),
    ("plural", "plural", "plural [ ˈplʊə.r ə l ] — множественное число"),
    ("anger", "anger", "anger [ ˈæŋ.ɡə r ] — гнев"),
    ("claim", "claim", "claim [ kleɪm ] — запрос / требовать"),
    ("price", "price", "price [ praɪs ] — цена");

