plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlin.compose)
}

android {
//    signingConfigs {
//        debug {
//            storeFile file('/Users/robertkalna/dev/android/kalnarapps/kalnardict_android/my-release-key.jks')
//            keyAlias 'my-alias'
//            storePassword '^3c#LPNz~2FbA22hi'
//        }
//    }
    compileSdkVersion 36
    defaultConfig {
        applicationId "eu.kalnarapps.kalnardict"
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    flavorDimensions "version"
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        mock {
            applicationIdSuffix ".mock"
        }
        full
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        compose true
    }
    packagingOptions {
        resources {
            excludes += 'META-INF/DEPENDENCIES'
            excludes += 'META-INF/DEPENDENCIES'
            excludes += 'META-INF/INDEX.LIST'
            excludes += 'META-INF/io.netty.versions.properties'
        }
    }

    namespace 'eu.kalnarapps.kalnardict'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:common")
    implementation project(":presentation")
    implementation project(":presentation:androidui")
    implementation project(":core:interactors")
    implementation project(":core:domain")
    implementation project(":core:data")
    implementation project(":localdata")
    implementation libs.compose.runtime.livedata

    def composeBom = platform(libs.compose.bom)
    implementation composeBom
    androidTestImplementation composeBom
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.androidx.activity.compose
    implementation libs.androidx.navigation.compose
    debugImplementation libs.compose.ui.tooling

    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx

    androidTestImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation(libs.androidx.test.ext.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation(libs.androidx.espresso.core) {
        exclude group: 'org.hamcrest'
    }

    implementation libs.koin.core
    implementation libs.koin.core.ext
    testImplementation libs.koin.test
    implementation libs.koin.android
    implementation libs.koin.android.ext

    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler
    kspAndroidTest libs.androidx.room.compiler
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.guava

    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.fragment

    debugImplementation libs.stetho

    testImplementation libs.hamcrest

    // Firebase
    implementation libs.firebase.appdistribution
    implementation libs.firebase.appdistribution.gradle
}

//android.applicationVariants.all { variant ->
//    if (variant.flavorName != "mock") {
//        // the Google services Gradle plugin
//        apply plugin: 'com.google.gms.google-services'
//        apply plugin: 'com.google.firebase.appdistribution'
//    }
//}
