apply plugin: 'com.android.application'
apply plugin: 'com.google.devtools.ksp'

android {
//    signingConfigs {
//        debug {
//            storeFile file('/Users/robertkalna/dev/android/kalnarapps/kalnardict_android/my-release-key.jks')
//            keyAlias 'my-alias'
//            storePassword '^3c#LPNz~2FbA22hi'
//        }
//    }
    compileSdkVersion 36
    defaultConfig {
        applicationId "eu.kalnarapps.kalnardict"
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    flavorDimensions "version"
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        mock {
            applicationIdSuffix ".mock"
        }
        full
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += 'META-INF/DEPENDENCIES'
        }
    }

    namespace 'eu.kalnarapps.kalnardict'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:common")
    implementation project(":presentation")
    implementation project(":presentation:androidui")
    implementation project(":core:interactors")
    implementation project(":core:domain")
    implementation project(":core:data")
    implementation project(":localdata")

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    // https://mvnrepository.com/artifact/org.hamcrest/hamcrest
    androidTestImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'
    testImplementation('junit:junit:4.12') {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation('androidx.test.ext:junit:1.1.3') {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    androidTestImplementation('androidx.test.espresso:espresso-core:3.4.0') {
        exclude group: 'org.hamcrest'
    }

    // latest stable
    def koin_version = '4.1.1'
    implementation "io.insert-koin:koin-core:$koin_version"
    // Koin extended & experimental features
    implementation "io.insert-koin:koin-core-ext:3.0.2"
    // Koin for Unit tests
    testImplementation "io.insert-koin:koin-test:$koin_version"
    implementation "io.insert-koin:koin-android:$koin_version"
    implementation "io.insert-koin:koin-android-ext:3.0.2"


    def room_version = "2.4.1"

    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    kspAndroidTest "androidx.room:room-compiler:$room_version"

    // optional - Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"

    // optional - Guava support for Room, including Optional and ListenableFuture
    implementation "androidx.room:room-guava:$room_version"

//    implementation 'io.insert-koin:koin-androidx-viewmodel:2.2.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.2.2'
    implementation "androidx.navigation:navigation-fragment-ktx:2.3.0-alpha06"
    implementation "androidx.fragment:fragment:1.3.0-alpha04"

    implementation "androidx.constraintlayout:constraintlayout:2.0.0-beta6"

    // stetho
    debugImplementation 'com.facebook.stetho:stetho:1.5.1'

    // test
    testImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'

    // Firebase
    // Import the Firebase BoM
//    implementation platform('com.google.firebase:firebase-bom:32.0.0')

    implementation 'com.google.firebase:firebase-appdistribution:16.0.0-beta08'
//    implementation 'com.google.firebase:firebase-appdistribution-gradle'
    implementation 'com.google.firebase:firebase-appdistribution-gradle:4.0.0'
//    com.google.firebase:firebase-appdistribution-api-ktx	16.0.0-beta08
    // Add the dependencies for any other desired Firebase products
    // https://firebase.google.com/docs/android/setup#available-libraries


}

//android.applicationVariants.all { variant ->
//    if (variant.flavorName != "mock") {
//        // the Google services Gradle plugin
//        apply plugin: 'com.google.gms.google-services'
//        apply plugin: 'com.google.firebase.appdistribution'
//    }
//}