apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "androidx.navigation.safeargs.kotlin"

android {
    compileSdkVersion 31

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 31

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    flavorDimensions "version"
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        mock
        full
    }
    sourceSets {
        main {
            res.srcDirs = getLayoutDirectories()
            res.srcDirs += [
                    'src/main/res/layouts',
                    'src/main/res'
            ]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

}

def getLayoutDirectories() {
    def layouts = []
    new File("${project.projectDir}/src/main/res/layouts/").eachDir() { dir ->
        layouts << "src/main/res/layouts/${dir.name}"
    }
    return layouts
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:common")
    implementation project(":presentation")
    mockImplementation project(path: ':core:domain')


    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.7.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // ui testing
    androidTestImplementation 'androidx.test:runner:1.4.0'
    androidTestImplementation 'androidx.test:rules:1.4.0'

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0-alpha02'
    implementation 'org.koin:koin-androidx-viewmodel:2.0.0-beta-4'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "androidx.recyclerview:recyclerview:1.1.0"

    // latest stable
    def koin_version = '2.0.1'
    // Koin for Kotlin
    implementation "org.koin:koin-core:$koin_version"
    // Koin extended & experimental features
    implementation "org.koin:koin-core-ext:$koin_version"

    implementation "org.koin:koin-androidx-scope:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"

    // Koin for Unit tests
    testImplementation "org.koin:koin-test:$koin_version"
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-android-ext:$koin_version"
    implementation "org.koin:koin-android-architecture:0.9.1"

    def nav_version = "2.3.0"
    implementation "androidx.fragment:fragment:1.3.0-alpha06"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"

    // coroutines for test
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.6'

    def lifecycle_version = "2.4.1"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

    // livedata testing
    testImplementation 'androidx.arch.core:core-testing:2.1.0'
    testImplementation 'com.jraska.livedata:testing-ktx:1.1.2'

    // unit test libraries
    testImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'
    testImplementation('junit:junit:4.12') {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }

    // ui
    implementation 'com.google.android.material:material:1.1.0'
    implementation "com.afollestad.material-dialogs:core:3.1.0"

    // logging
    implementation 'com.orhanobut:logger:2.2.0'

    // mock libraries
    implementation 'org.mockito:mockito-core:3.4.4'
}
