plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.navigation.safeargs.kotlin)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    flavorDimensions "version"
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        mock
        full
    }

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion "1.5.8"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
            // TODO: why de we need to do this ? two libraries seem to include the same files
            excludes += 'win32-x86-64/attach_hotspot_windows.dll'
            excludes += 'win32-x86/attach_hotspot_windows.dll'
            excludes += 'META-INF/licenses/ASM'
        }
    }
    namespace 'eu.kalnarapps.kalnardict.androidui'

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:common")
    implementation project(":presentation")
    implementation project(":platform:android:common")
    testImplementation project(":core:test")
    mockImplementation project(path: ':core:domain')

    implementation libs.commons.lang3

    implementation libs.kotlin.stdlib
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    testImplementation libs.junit4
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.espresso.core

    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules

    implementation libs.androidx.lifecycle.viewmodel.ktx

    implementation libs.koin.core
    implementation libs.koin.core.ext
    implementation libs.koin.androidx.compose
    testImplementation libs.koin.test
    implementation libs.koin.android
    implementation libs.koin.android.ext

    implementation libs.androidx.fragment
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.fragment.ktx

    testImplementation libs.kotlinx.coroutines.test

    implementation libs.androidx.lifecycle.livedata.ktx
    testImplementation libs.androidx.arch.core.testing
    testImplementation libs.jraska.livedata.testing.ktx

    testImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }

    implementation libs.google.material
    implementation libs.material.dialogs.core

    implementation libs.orhanobut.logger

    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin

    // compose
    def composeBom = platform(libs.compose.bom)
    implementation composeBom
    androidTestImplementation composeBom
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.androidx.activity.compose
    implementation libs.androidx.navigation.compose
    debugImplementation libs.compose.ui.tooling

    implementation libs.kotlinx.serialization.json

    implementation libs.compose.foundation
    implementation libs.compose.material
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.compose.runtime.livedata
    implementation libs.google.compose.theme.adapter
    implementation(libs.androidx.material.icons.core)
    implementation(libs.androidx.material.icons.extended) // optional

    androidTestImplementation libs.compose.ui.test.junit4
    androidTestImplementation libs.compose.ui.test.manifest
}
