apply plugin: 'java-library'
apply plugin: 'kotlin'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // https://mvnrepository.com/artifact/org.hamcrest/hamcrest
    testImplementation group: 'org.hamcrest', name: 'hamcrest', version: '2.2'
    testImplementation('junit:junit:4.12') {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation('androidx.test.ext:junit:1.1.1') {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation('androidx.test.espresso:espresso-core:3.1.1') {
        exclude group: 'org.hamcrest'
    }
}

sourceCompatibility = "7"
targetCompatibility = "7"
