plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":core:common")
    implementation libs.kotlin.stdlib
    testImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation(libs.androidx.test.ext.junit) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    testImplementation(libs.androidx.espresso.core) {
        exclude group: 'org.hamcrest'
    }

    implementation libs.kotlinx.coroutines.core
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
}
