plugins {
    id 'java-library'
    alias(libs.plugins.kotlin.jvm)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":core:domain")
    implementation project(":core:common")
    implementation libs.kotlin.stdlib
    implementation libs.junit4

    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.hamcrest
    testImplementation(libs.junit4) {
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }
    implementation libs.kotlinx.coroutines.core

    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
}
